// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_surface.sql

package sqlcgen

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminActiveUsers = `-- name: AdminActiveUsers :one
SELECT count(*) FROM users WHERE status = 'active'
`

func (q *Queries) AdminActiveUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, adminActiveUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminAuditByResource = `-- name: AdminAuditByResource :many
SELECT id, actor_type, actor_id, action, resource_type, resource_id, created_at
FROM audit_events
WHERE resource_type = $1 AND resource_id = $2
ORDER BY created_at DESC
LIMIT 50
`

type AdminAuditByResourceParams struct {
	ResourceType string     `json:"resource_type"`
	ResourceID   *uuid.UUID `json:"resource_id"`
}

type AdminAuditByResourceRow struct {
	ID           uuid.UUID          `json:"id"`
	ActorType    string             `json:"actor_type"`
	ActorID      *uuid.UUID         `json:"actor_id"`
	Action       string             `json:"action"`
	ResourceType string             `json:"resource_type"`
	ResourceID   *uuid.UUID         `json:"resource_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) AdminAuditByResource(ctx context.Context, arg AdminAuditByResourceParams) ([]AdminAuditByResourceRow, error) {
	rows, err := q.db.Query(ctx, adminAuditByResource, arg.ResourceType, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminAuditByResourceRow{}
	for rows.Next() {
		var i AdminAuditByResourceRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorType,
			&i.ActorID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminAuditRecent = `-- name: AdminAuditRecent :many

SELECT id, actor_type, actor_id, action, resource_type, resource_id, created_at
FROM audit_events
ORDER BY created_at DESC
LIMIT 100
`

type AdminAuditRecentRow struct {
	ID           uuid.UUID          `json:"id"`
	ActorType    string             `json:"actor_type"`
	ActorID      *uuid.UUID         `json:"actor_id"`
	Action       string             `json:"action"`
	ResourceType string             `json:"resource_type"`
	ResourceID   *uuid.UUID         `json:"resource_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

// ---------------------------------------------------------------------- audit --
func (q *Queries) AdminAuditRecent(ctx context.Context) ([]AdminAuditRecentRow, error) {
	rows, err := q.db.Query(ctx, adminAuditRecent)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminAuditRecentRow{}
	for rows.Next() {
		var i AdminAuditRecentRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorType,
			&i.ActorID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminCapacityWarnings = `-- name: AdminCapacityWarnings :one
SELECT count(*)
FROM nodes n
JOIN node_groups g ON g.id = n.node_group_id
WHERE n.status = 'online'
  AND g.cpu_cores_total > 0
  AND (g.cpu_cores_total - n.cpu_cores_available) * 100.0 / g.cpu_cores_total >= 80.0
`

func (q *Queries) AdminCapacityWarnings(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, adminCapacityWarnings)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminInstanceDetail = `-- name: AdminInstanceDetail :one
SELECT i.id, i.subscription_id, i.node_id, i.provider_id, i.provider_instance_id, i.name, i.desired_state, i.observed_state, i.cpu_cores, i.memory_mb, i.disk_gb, i.traffic_limit_gb, i.bandwidth_mbps, i.image_id, i.primary_ipv4, i.primary_ipv6, i.last_synced_at, i.version, i.created_at, i.updated_at, i.deleted_at, u.email AS user_email, s.status AS subscription_status,
       pl.name_i18n AS plan_name_i18n, pl.virtualization AS plan_virtualization,
       n.name AS node_name, p.name AS provider_name
FROM instances i
JOIN subscriptions s ON s.id = i.subscription_id
JOIN users u ON u.id = s.user_id
JOIN plans pl ON pl.id = s.plan_id
LEFT JOIN nodes n ON n.id = i.node_id
LEFT JOIN providers p ON p.id = i.provider_id
WHERE i.id = $1 AND i.deleted_at IS NULL
`

type AdminInstanceDetailRow struct {
	ID                 uuid.UUID          `json:"id"`
	SubscriptionID     uuid.UUID          `json:"subscription_id"`
	NodeID             *uuid.UUID         `json:"node_id"`
	ProviderID         *uuid.UUID         `json:"provider_id"`
	ProviderInstanceID pgtype.Text        `json:"provider_instance_id"`
	Name               string             `json:"name"`
	DesiredState       string             `json:"desired_state"`
	ObservedState      string             `json:"observed_state"`
	CpuCores           pgtype.Numeric     `json:"cpu_cores"`
	MemoryMb           int32              `json:"memory_mb"`
	DiskGb             int32              `json:"disk_gb"`
	TrafficLimitGb     pgtype.Int8        `json:"traffic_limit_gb"`
	BandwidthMbps      pgtype.Int4        `json:"bandwidth_mbps"`
	ImageID            pgtype.Text        `json:"image_id"`
	PrimaryIpv4        *netip.Addr        `json:"primary_ipv4"`
	PrimaryIpv6        *netip.Addr        `json:"primary_ipv6"`
	LastSyncedAt       pgtype.Timestamptz `json:"last_synced_at"`
	Version            int64              `json:"version"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	UserEmail          string             `json:"user_email"`
	SubscriptionStatus string             `json:"subscription_status"`
	PlanNameI18n       []byte             `json:"plan_name_i18n"`
	PlanVirtualization string             `json:"plan_virtualization"`
	NodeName           pgtype.Text        `json:"node_name"`
	ProviderName       pgtype.Text        `json:"provider_name"`
}

func (q *Queries) AdminInstanceDetail(ctx context.Context, id uuid.UUID) (AdminInstanceDetailRow, error) {
	row := q.db.QueryRow(ctx, adminInstanceDetail, id)
	var i AdminInstanceDetailRow
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.NodeID,
		&i.ProviderID,
		&i.ProviderInstanceID,
		&i.Name,
		&i.DesiredState,
		&i.ObservedState,
		&i.CpuCores,
		&i.MemoryMb,
		&i.DiskGb,
		&i.TrafficLimitGb,
		&i.BandwidthMbps,
		&i.ImageID,
		&i.PrimaryIpv4,
		&i.PrimaryIpv6,
		&i.LastSyncedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserEmail,
		&i.SubscriptionStatus,
		&i.PlanNameI18n,
		&i.PlanVirtualization,
		&i.NodeName,
		&i.ProviderName,
	)
	return i, err
}

const adminLedgerMovements = `-- name: AdminLedgerMovements :many

SELECT lt.type AS transaction_type, lt.reference_type, lt.reference_id,
       lt.description, le.account_type, le.account_id, le.direction,
       le.amount_minor, le.currency, le.created_at
FROM ledger_entries le
JOIN ledger_transactions lt ON lt.id = le.transaction_id
ORDER BY le.created_at DESC
LIMIT 100
`

type AdminLedgerMovementsRow struct {
	TransactionType string             `json:"transaction_type"`
	ReferenceType   pgtype.Text        `json:"reference_type"`
	ReferenceID     *uuid.UUID         `json:"reference_id"`
	Description     pgtype.Text        `json:"description"`
	AccountType     string             `json:"account_type"`
	AccountID       uuid.UUID          `json:"account_id"`
	Direction       string             `json:"direction"`
	AmountMinor     int64              `json:"amount_minor"`
	Currency        string             `json:"currency"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

// --------------------------------------------------------------------- ledger --
func (q *Queries) AdminLedgerMovements(ctx context.Context) ([]AdminLedgerMovementsRow, error) {
	rows, err := q.db.Query(ctx, adminLedgerMovements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminLedgerMovementsRow{}
	for rows.Next() {
		var i AdminLedgerMovementsRow
		if err := rows.Scan(
			&i.TransactionType,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.Description,
			&i.AccountType,
			&i.AccountID,
			&i.Direction,
			&i.AmountMinor,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListAdmins = `-- name: AdminListAdmins :many

SELECT a.id, a.email, a.status, a.display_name, a.two_factor_enabled, a.created_at
FROM admins a
ORDER BY a.created_at DESC
`

type AdminListAdminsRow struct {
	ID               uuid.UUID          `json:"id"`
	Email            string             `json:"email"`
	Status           string             `json:"status"`
	DisplayName      pgtype.Text        `json:"display_name"`
	TwoFactorEnabled bool               `json:"two_factor_enabled"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

// ------------------------------------------------------- admins/roles/settings --
func (q *Queries) AdminListAdmins(ctx context.Context) ([]AdminListAdminsRow, error) {
	rows, err := q.db.Query(ctx, adminListAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListAdminsRow{}
	for rows.Next() {
		var i AdminListAdminsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Status,
			&i.DisplayName,
			&i.TwoFactorEnabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListInstances = `-- name: AdminListInstances :many

SELECT i.id, i.name, i.desired_state, i.observed_state, i.cpu_cores::text AS cpu_cores_text,
       i.memory_mb, i.disk_gb, i.provider_instance_id, i.last_synced_at, i.created_at,
       u.email AS user_email, n.name AS node_name, p.name AS provider_name
FROM instances i
JOIN subscriptions s ON s.id = i.subscription_id
JOIN users u ON u.id = s.user_id
LEFT JOIN nodes n ON n.id = i.node_id
LEFT JOIN providers p ON p.id = i.provider_id
WHERE i.deleted_at IS NULL
ORDER BY i.created_at DESC
LIMIT 100
`

type AdminListInstancesRow struct {
	ID                 uuid.UUID          `json:"id"`
	Name               string             `json:"name"`
	DesiredState       string             `json:"desired_state"`
	ObservedState      string             `json:"observed_state"`
	CpuCoresText       string             `json:"cpu_cores_text"`
	MemoryMb           int32              `json:"memory_mb"`
	DiskGb             int32              `json:"disk_gb"`
	ProviderInstanceID pgtype.Text        `json:"provider_instance_id"`
	LastSyncedAt       pgtype.Timestamptz `json:"last_synced_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UserEmail          string             `json:"user_email"`
	NodeName           pgtype.Text        `json:"node_name"`
	ProviderName       pgtype.Text        `json:"provider_name"`
}

// ------------------------------------------------------------------ instances --
func (q *Queries) AdminListInstances(ctx context.Context) ([]AdminListInstancesRow, error) {
	rows, err := q.db.Query(ctx, adminListInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListInstancesRow{}
	for rows.Next() {
		var i AdminListInstancesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DesiredState,
			&i.ObservedState,
			&i.CpuCoresText,
			&i.MemoryMb,
			&i.DiskGb,
			&i.ProviderInstanceID,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UserEmail,
			&i.NodeName,
			&i.ProviderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListOperations = `-- name: AdminListOperations :many
SELECT id, type, resource_type, resource_id, status, phase, progress, message_key, provider_id, provider_operation_id, idempotency_key, retryable, retry_count, max_retries, run_after, error_code, error_message, trace_id, started_at, finished_at, created_at, updated_at FROM operations ORDER BY created_at DESC LIMIT 100
`

func (q *Queries) AdminListOperations(ctx context.Context) ([]Operation, error) {
	rows, err := q.db.Query(ctx, adminListOperations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Operation{}
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.ResourceType,
			&i.ResourceID,
			&i.Status,
			&i.Phase,
			&i.Progress,
			&i.MessageKey,
			&i.ProviderID,
			&i.ProviderOperationID,
			&i.IdempotencyKey,
			&i.Retryable,
			&i.RetryCount,
			&i.MaxRetries,
			&i.RunAfter,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.TraceID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListOrders = `-- name: AdminListOrders :many

SELECT o.id, o.order_no, o.user_id, u.email AS user_email, o.status,
       o.subtotal_minor, o.discount_minor, o.total_minor, o.currency, o.paid_at, o.created_at
FROM orders o
JOIN users u ON u.id = o.user_id
ORDER BY o.created_at DESC
LIMIT 100
`

type AdminListOrdersRow struct {
	ID            uuid.UUID          `json:"id"`
	OrderNo       string             `json:"order_no"`
	UserID        uuid.UUID          `json:"user_id"`
	UserEmail     string             `json:"user_email"`
	Status        string             `json:"status"`
	SubtotalMinor int64              `json:"subtotal_minor"`
	DiscountMinor int64              `json:"discount_minor"`
	TotalMinor    int64              `json:"total_minor"`
	Currency      string             `json:"currency"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

// --------------------------------------------------------------------- orders --
func (q *Queries) AdminListOrders(ctx context.Context) ([]AdminListOrdersRow, error) {
	rows, err := q.db.Query(ctx, adminListOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListOrdersRow{}
	for rows.Next() {
		var i AdminListOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderNo,
			&i.UserID,
			&i.UserEmail,
			&i.Status,
			&i.SubtotalMinor,
			&i.DiscountMinor,
			&i.TotalMinor,
			&i.Currency,
			&i.PaidAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListPayments = `-- name: AdminListPayments :many
SELECT p.id, p.payment_no, p.order_id, p.gateway, p.status, p.amount_minor, p.currency,
       p.created_at, o.order_no
FROM payments p
JOIN orders o ON o.id = p.order_id
ORDER BY p.created_at DESC
LIMIT 100
`

type AdminListPaymentsRow struct {
	ID          uuid.UUID          `json:"id"`
	PaymentNo   string             `json:"payment_no"`
	OrderID     uuid.UUID          `json:"order_id"`
	Gateway     string             `json:"gateway"`
	Status      string             `json:"status"`
	AmountMinor int64              `json:"amount_minor"`
	Currency    string             `json:"currency"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	OrderNo     string             `json:"order_no"`
}

func (q *Queries) AdminListPayments(ctx context.Context) ([]AdminListPaymentsRow, error) {
	rows, err := q.db.Query(ctx, adminListPayments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListPaymentsRow{}
	for rows.Next() {
		var i AdminListPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PaymentNo,
			&i.OrderID,
			&i.Gateway,
			&i.Status,
			&i.AmountMinor,
			&i.Currency,
			&i.CreatedAt,
			&i.OrderNo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListPlans = `-- name: AdminListPlans :many
SELECT id, product_id, slug, status, memory_mb, disk_gb, traffic_gb, bandwidth_mbps,
       ipv4_count, ipv6_count, nat_port_count, virtualization, billing_cycle,
       price_minor, currency,
       cpu_cores::text AS cpu_cores_text
FROM plans ORDER BY price_minor, slug
`

type AdminListPlansRow struct {
	ID             uuid.UUID   `json:"id"`
	ProductID      uuid.UUID   `json:"product_id"`
	Slug           string      `json:"slug"`
	Status         string      `json:"status"`
	MemoryMb       int32       `json:"memory_mb"`
	DiskGb         int32       `json:"disk_gb"`
	TrafficGb      pgtype.Int8 `json:"traffic_gb"`
	BandwidthMbps  pgtype.Int4 `json:"bandwidth_mbps"`
	Ipv4Count      int32       `json:"ipv4_count"`
	Ipv6Count      int32       `json:"ipv6_count"`
	NatPortCount   int32       `json:"nat_port_count"`
	Virtualization string      `json:"virtualization"`
	BillingCycle   string      `json:"billing_cycle"`
	PriceMinor     int64       `json:"price_minor"`
	Currency       string      `json:"currency"`
	CpuCoresText   string      `json:"cpu_cores_text"`
}

func (q *Queries) AdminListPlans(ctx context.Context) ([]AdminListPlansRow, error) {
	rows, err := q.db.Query(ctx, adminListPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListPlansRow{}
	for rows.Next() {
		var i AdminListPlansRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Slug,
			&i.Status,
			&i.MemoryMb,
			&i.DiskGb,
			&i.TrafficGb,
			&i.BandwidthMbps,
			&i.Ipv4Count,
			&i.Ipv6Count,
			&i.NatPortCount,
			&i.Virtualization,
			&i.BillingCycle,
			&i.PriceMinor,
			&i.Currency,
			&i.CpuCoresText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListProducts = `-- name: AdminListProducts :many

SELECT id, slug, name_i18n, description_i18n, status, sort_order, created_at, updated_at FROM products ORDER BY sort_order, slug
`

// ------------------------------------------------------------------- products --
func (q *Queries) AdminListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, adminListProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.NameI18n,
			&i.DescriptionI18n,
			&i.Status,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListRoles = `-- name: AdminListRoles :many
SELECT id, key, name_key FROM roles ORDER BY key
`

type AdminListRolesRow struct {
	ID      uuid.UUID `json:"id"`
	Key     string    `json:"key"`
	NameKey string    `json:"name_key"`
}

func (q *Queries) AdminListRoles(ctx context.Context) ([]AdminListRolesRow, error) {
	rows, err := q.db.Query(ctx, adminListRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListRolesRow{}
	for rows.Next() {
		var i AdminListRolesRow
		if err := rows.Scan(&i.ID, &i.Key, &i.NameKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListSettings = `-- name: AdminListSettings :many
SELECT key, value, description, updated_at, updated_by FROM system_settings ORDER BY key
`

func (q *Queries) AdminListSettings(ctx context.Context) ([]SystemSetting, error) {
	rows, err := q.db.Query(ctx, adminListSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemSetting{}
	for rows.Next() {
		var i SystemSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Description,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListSubscriptions = `-- name: AdminListSubscriptions :many

SELECT s.id, s.user_id, u.email AS user_email, s.status, pl.name_i18n AS plan_name_i18n,
       s.billing_cycle, s.price_minor, s.currency, s.current_period_start, s.current_period_end, s.created_at
FROM subscriptions s
JOIN users u ON u.id = s.user_id
JOIN plans pl ON pl.id = s.plan_id
ORDER BY s.created_at DESC
LIMIT 100
`

type AdminListSubscriptionsRow struct {
	ID                 uuid.UUID          `json:"id"`
	UserID             uuid.UUID          `json:"user_id"`
	UserEmail          string             `json:"user_email"`
	Status             string             `json:"status"`
	PlanNameI18n       []byte             `json:"plan_name_i18n"`
	BillingCycle       string             `json:"billing_cycle"`
	PriceMinor         int64              `json:"price_minor"`
	Currency           string             `json:"currency"`
	CurrentPeriodStart pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd   pgtype.Timestamptz `json:"current_period_end"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

// -------------------------------------------------------------- subscriptions --
func (q *Queries) AdminListSubscriptions(ctx context.Context) ([]AdminListSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, adminListSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListSubscriptionsRow{}
	for rows.Next() {
		var i AdminListSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserEmail,
			&i.Status,
			&i.PlanNameI18n,
			&i.BillingCycle,
			&i.PriceMinor,
			&i.Currency,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListTickets = `-- name: AdminListTickets :many

SELECT t.id, t.ticket_no, t.subject, t.status, t.priority, t.created_at, t.updated_at,
       u.email AS user_email
FROM tickets t
JOIN users u ON u.id = t.user_id
ORDER BY t.updated_at DESC
LIMIT 100
`

type AdminListTicketsRow struct {
	ID        uuid.UUID          `json:"id"`
	TicketNo  string             `json:"ticket_no"`
	Subject   string             `json:"subject"`
	Status    string             `json:"status"`
	Priority  string             `json:"priority"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UserEmail string             `json:"user_email"`
}

// -------------------------------------------------------------------- tickets --
func (q *Queries) AdminListTickets(ctx context.Context) ([]AdminListTicketsRow, error) {
	rows, err := q.db.Query(ctx, adminListTickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListTicketsRow{}
	for rows.Next() {
		var i AdminListTicketsRow
		if err := rows.Scan(
			&i.ID,
			&i.TicketNo,
			&i.Subject,
			&i.Status,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListUsers = `-- name: AdminListUsers :many

SELECT id, email, status, locale, created_at FROM users ORDER BY created_at DESC LIMIT 100
`

type AdminListUsersRow struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	Status    string             `json:"status"`
	Locale    string             `json:"locale"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// ---------------------------------------------------------------------- users --
func (q *Queries) AdminListUsers(ctx context.Context) ([]AdminListUsersRow, error) {
	rows, err := q.db.Query(ctx, adminListUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListUsersRow{}
	for rows.Next() {
		var i AdminListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Status,
			&i.Locale,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminNodesOffline = `-- name: AdminNodesOffline :one
SELECT count(*) FROM nodes WHERE status <> 'online'
`

func (q *Queries) AdminNodesOffline(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, adminNodesOffline)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminOpenFailedOperations = `-- name: AdminOpenFailedOperations :one


SELECT count(*) FROM operations WHERE status IN ('failed', 'retrying')
`

// The operator's surface (ADR-012): lists, details and the dashboard's
// computed aggregates. Every statement is a read behind a declared permission;
// the few writes are conditional updates that name the state they move.
// ------------------------------------------------------------------ overview --
func (q *Queries) AdminOpenFailedOperations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, adminOpenFailedOperations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminOperationsByResource = `-- name: AdminOperationsByResource :many
SELECT id, type, resource_type, resource_id, status, phase, progress, message_key, provider_id, provider_operation_id, idempotency_key, retryable, retry_count, max_retries, run_after, error_code, error_message, trace_id, started_at, finished_at, created_at, updated_at FROM operations
WHERE resource_type = $1 AND resource_id = $2
ORDER BY created_at DESC
LIMIT 50
`

type AdminOperationsByResourceParams struct {
	ResourceType string    `json:"resource_type"`
	ResourceID   uuid.UUID `json:"resource_id"`
}

func (q *Queries) AdminOperationsByResource(ctx context.Context, arg AdminOperationsByResourceParams) ([]Operation, error) {
	rows, err := q.db.Query(ctx, adminOperationsByResource, arg.ResourceType, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Operation{}
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.ResourceType,
			&i.ResourceID,
			&i.Status,
			&i.Phase,
			&i.Progress,
			&i.MessageKey,
			&i.ProviderID,
			&i.ProviderOperationID,
			&i.IdempotencyKey,
			&i.Retryable,
			&i.RetryCount,
			&i.MaxRetries,
			&i.RunAfter,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.TraceID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminOrderByID = `-- name: AdminOrderByID :one
SELECT o.id, o.order_no, o.user_id, o.status, o.subtotal_minor, o.discount_minor, o.total_minor, o.currency, o.paid_at, o.created_at, o.updated_at, u.email AS user_email
FROM orders o
JOIN users u ON u.id = o.user_id
WHERE o.id = $1
`

type AdminOrderByIDRow struct {
	ID            uuid.UUID          `json:"id"`
	OrderNo       string             `json:"order_no"`
	UserID        uuid.UUID          `json:"user_id"`
	Status        string             `json:"status"`
	SubtotalMinor int64              `json:"subtotal_minor"`
	DiscountMinor int64              `json:"discount_minor"`
	TotalMinor    int64              `json:"total_minor"`
	Currency      string             `json:"currency"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	UserEmail     string             `json:"user_email"`
}

func (q *Queries) AdminOrderByID(ctx context.Context, id uuid.UUID) (AdminOrderByIDRow, error) {
	row := q.db.QueryRow(ctx, adminOrderByID, id)
	var i AdminOrderByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.UserID,
		&i.Status,
		&i.SubtotalMinor,
		&i.DiscountMinor,
		&i.TotalMinor,
		&i.Currency,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserEmail,
	)
	return i, err
}

const adminOrderItems = `-- name: AdminOrderItems :many
SELECT id, order_id, product_id, plan_id, quantity, unit_price_minor, total_minor, product_snapshot, plan_snapshot, created_at FROM order_items WHERE order_id = $1 ORDER BY created_at
`

func (q *Queries) AdminOrderItems(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, adminOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.PlanID,
			&i.Quantity,
			&i.UnitPriceMinor,
			&i.TotalMinor,
			&i.ProductSnapshot,
			&i.PlanSnapshot,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminOrderPayments = `-- name: AdminOrderPayments :many
SELECT id, payment_no, gateway, status, amount_minor, currency, created_at
FROM payments WHERE order_id = $1 ORDER BY created_at
`

type AdminOrderPaymentsRow struct {
	ID          uuid.UUID          `json:"id"`
	PaymentNo   string             `json:"payment_no"`
	Gateway     string             `json:"gateway"`
	Status      string             `json:"status"`
	AmountMinor int64              `json:"amount_minor"`
	Currency    string             `json:"currency"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) AdminOrderPayments(ctx context.Context, orderID uuid.UUID) ([]AdminOrderPaymentsRow, error) {
	rows, err := q.db.Query(ctx, adminOrderPayments, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminOrderPaymentsRow{}
	for rows.Next() {
		var i AdminOrderPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PaymentNo,
			&i.Gateway,
			&i.Status,
			&i.AmountMinor,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminPaymentsByStatus = `-- name: AdminPaymentsByStatus :many
SELECT status, count(*) AS count FROM payments GROUP BY status
`

type AdminPaymentsByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) AdminPaymentsByStatus(ctx context.Context) ([]AdminPaymentsByStatusRow, error) {
	rows, err := q.db.Query(ctx, adminPaymentsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminPaymentsByStatusRow{}
	for rows.Next() {
		var i AdminPaymentsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminPermissionsByRole = `-- name: AdminPermissionsByRole :many
SELECT rp.role_id, p.key
FROM role_permissions rp
JOIN permissions p ON p.id = rp.permission_id
`

type AdminPermissionsByRoleRow struct {
	RoleID uuid.UUID `json:"role_id"`
	Key    string    `json:"key"`
}

func (q *Queries) AdminPermissionsByRole(ctx context.Context) ([]AdminPermissionsByRoleRow, error) {
	rows, err := q.db.Query(ctx, adminPermissionsByRole)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminPermissionsByRoleRow{}
	for rows.Next() {
		var i AdminPermissionsByRoleRow
		if err := rows.Scan(&i.RoleID, &i.Key); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminRevenueTotal = `-- name: AdminRevenueTotal :one
SELECT COALESCE(sum(amount_minor), 0)::bigint FROM payments WHERE status = 'succeeded'
`

func (q *Queries) AdminRevenueTotal(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, adminRevenueTotal)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const adminRolesByAdmin = `-- name: AdminRolesByAdmin :many
SELECT r.id, r.key, ar.admin_id
FROM admin_roles ar
JOIN roles r ON r.id = ar.role_id
`

type AdminRolesByAdminRow struct {
	ID      uuid.UUID `json:"id"`
	Key     string    `json:"key"`
	AdminID uuid.UUID `json:"admin_id"`
}

func (q *Queries) AdminRolesByAdmin(ctx context.Context) ([]AdminRolesByAdminRow, error) {
	rows, err := q.db.Query(ctx, adminRolesByAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminRolesByAdminRow{}
	for rows.Next() {
		var i AdminRolesByAdminRow
		if err := rows.Scan(&i.ID, &i.Key, &i.AdminID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminRunningOperations = `-- name: AdminRunningOperations :one
SELECT count(*) FROM operations WHERE status IN ('queued', 'running', 'waiting_provider', 'waiting_resource', 'verifying')
`

func (q *Queries) AdminRunningOperations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, adminRunningOperations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminSetUserStatus = `-- name: AdminSetUserStatus :execrows
UPDATE users SET status = $2, updated_at = $3 WHERE id = $1 AND status <> $2
`

type AdminSetUserStatusParams struct {
	ID        uuid.UUID          `json:"id"`
	Status    string             `json:"status"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) AdminSetUserStatus(ctx context.Context, arg AdminSetUserStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminSetUserStatus, arg.ID, arg.Status, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminSuspendedUsers = `-- name: AdminSuspendedUsers :one
SELECT count(*) FROM users WHERE status = 'suspended'
`

func (q *Queries) AdminSuspendedUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, adminSuspendedUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminTicketByID = `-- name: AdminTicketByID :one
SELECT t.id, t.ticket_no, t.user_id, t.subject, t.status, t.priority, t.created_at, t.updated_at, t.closed_at, u.email AS user_email
FROM tickets t
JOIN users u ON u.id = t.user_id
WHERE t.id = $1
`

type AdminTicketByIDRow struct {
	ID        uuid.UUID          `json:"id"`
	TicketNo  string             `json:"ticket_no"`
	UserID    uuid.UUID          `json:"user_id"`
	Subject   string             `json:"subject"`
	Status    string             `json:"status"`
	Priority  string             `json:"priority"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ClosedAt  pgtype.Timestamptz `json:"closed_at"`
	UserEmail string             `json:"user_email"`
}

func (q *Queries) AdminTicketByID(ctx context.Context, id uuid.UUID) (AdminTicketByIDRow, error) {
	row := q.db.QueryRow(ctx, adminTicketByID, id)
	var i AdminTicketByIDRow
	err := row.Scan(
		&i.ID,
		&i.TicketNo,
		&i.UserID,
		&i.Subject,
		&i.Status,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.UserEmail,
	)
	return i, err
}

const adminTicketClose = `-- name: AdminTicketClose :execrows
UPDATE tickets
SET status = 'closed', closed_at = $2, updated_at = $2
WHERE id = $1 AND status <> 'closed'
`

type AdminTicketCloseParams struct {
	ID       uuid.UUID          `json:"id"`
	ClosedAt pgtype.Timestamptz `json:"closed_at"`
}

func (q *Queries) AdminTicketClose(ctx context.Context, arg AdminTicketCloseParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminTicketClose, arg.ID, arg.ClosedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminTicketReplyStamp = `-- name: AdminTicketReplyStamp :execrows
UPDATE tickets
SET status = 'answered', updated_at = $2
WHERE id = $1 AND status <> 'closed'
`

type AdminTicketReplyStampParams struct {
	ID        uuid.UUID          `json:"id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) AdminTicketReplyStamp(ctx context.Context, arg AdminTicketReplyStampParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminTicketReplyStamp, arg.ID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminUserByID = `-- name: AdminUserByID :one
SELECT id, email, status, locale, timezone, created_at FROM users WHERE id = $1
`

type AdminUserByIDRow struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	Status    string             `json:"status"`
	Locale    string             `json:"locale"`
	Timezone  string             `json:"timezone"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) AdminUserByID(ctx context.Context, id uuid.UUID) (AdminUserByIDRow, error) {
	row := q.db.QueryRow(ctx, adminUserByID, id)
	var i AdminUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Status,
		&i.Locale,
		&i.Timezone,
		&i.CreatedAt,
	)
	return i, err
}

const adminUserWallets = `-- name: AdminUserWallets :many
SELECT id, currency, available_balance_minor FROM wallets WHERE user_id = $1 ORDER BY currency
`

type AdminUserWalletsRow struct {
	ID                    uuid.UUID `json:"id"`
	Currency              string    `json:"currency"`
	AvailableBalanceMinor int64     `json:"available_balance_minor"`
}

func (q *Queries) AdminUserWallets(ctx context.Context, userID uuid.UUID) ([]AdminUserWalletsRow, error) {
	rows, err := q.db.Query(ctx, adminUserWallets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminUserWalletsRow{}
	for rows.Next() {
		var i AdminUserWalletsRow
		if err := rows.Scan(&i.ID, &i.Currency, &i.AvailableBalanceMinor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminWalletBalances = `-- name: AdminWalletBalances :many
SELECT w.id, w.user_id, w.currency, w.available_balance_minor
FROM wallets w
ORDER BY w.user_id, w.currency
LIMIT 100
`

type AdminWalletBalancesRow struct {
	ID                    uuid.UUID `json:"id"`
	UserID                uuid.UUID `json:"user_id"`
	Currency              string    `json:"currency"`
	AvailableBalanceMinor int64     `json:"available_balance_minor"`
}

func (q *Queries) AdminWalletBalances(ctx context.Context) ([]AdminWalletBalancesRow, error) {
	rows, err := q.db.Query(ctx, adminWalletBalances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminWalletBalancesRow{}
	for rows.Next() {
		var i AdminWalletBalancesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Currency,
			&i.AvailableBalanceMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const metricsInstancesByState = `-- name: MetricsInstancesByState :many
SELECT observed_state, count(*) AS count FROM instances
WHERE deleted_at IS NULL GROUP BY observed_state
`

type MetricsInstancesByStateRow struct {
	ObservedState string `json:"observed_state"`
	Count         int64  `json:"count"`
}

func (q *Queries) MetricsInstancesByState(ctx context.Context) ([]MetricsInstancesByStateRow, error) {
	rows, err := q.db.Query(ctx, metricsInstancesByState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetricsInstancesByStateRow{}
	for rows.Next() {
		var i MetricsInstancesByStateRow
		if err := rows.Scan(&i.ObservedState, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const metricsOperationsByStatus = `-- name: MetricsOperationsByStatus :many
SELECT status, count(*) AS count FROM operations GROUP BY status
`

type MetricsOperationsByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) MetricsOperationsByStatus(ctx context.Context) ([]MetricsOperationsByStatusRow, error) {
	rows, err := q.db.Query(ctx, metricsOperationsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetricsOperationsByStatusRow{}
	for rows.Next() {
		var i MetricsOperationsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
