// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commerce.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendPaymentPayload = `-- name: AppendPaymentPayload :exec
UPDATE payments
SET gateway_payload = gateway_payload || $2::jsonb, updated_at = now()
WHERE id = $1
`

type AppendPaymentPayloadParams struct {
	ID      uuid.UUID `json:"id"`
	Column2 []byte    `json:"column_2"`
}

// Merged into what the gateway sent, rather than replacing it: the payload accumulates
// across the callbacks of one payment, which is what a dispute needs.
func (q *Queries) AppendPaymentPayload(ctx context.Context, arg AppendPaymentPayloadParams) error {
	_, err := q.db.Exec(ctx, appendPaymentPayload, arg.ID, arg.Column2)
	return err
}

const claimDueOutboxEvents = `-- name: ClaimDueOutboxEvents :many
UPDATE outbox_events
SET status = 'pending', attempts = attempts + 1, next_attempt_at = $1
WHERE id IN (
  SELECT o.id FROM outbox_events o
  WHERE o.status = 'pending' AND o.next_attempt_at <= $1
    AND o.event_type = ANY($2::text[])
  ORDER BY o.created_at
  FOR UPDATE SKIP LOCKED
  LIMIT 32
)
RETURNING id, event_type, aggregate_type, aggregate_id, payload, attempts, created_at
`

type ClaimDueOutboxEventsParams struct {
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	Column2       []string           `json:"column_2"`
}

type ClaimDueOutboxEventsRow struct {
	ID            uuid.UUID          `json:"id"`
	EventType     string             `json:"event_type"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   uuid.UUID          `json:"aggregate_id"`
	Payload       []byte             `json:"payload"`
	Attempts      int32              `json:"attempts"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

// The delivery side, owned by the worker (ADR-005): claim what is due under
// SKIP LOCKED, so N workers share the batch rather than racing over it.
func (q *Queries) ClaimDueOutboxEvents(ctx context.Context, arg ClaimDueOutboxEventsParams) ([]ClaimDueOutboxEventsRow, error) {
	rows, err := q.db.Query(ctx, claimDueOutboxEvents, arg.NextAttemptAt, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimDueOutboxEventsRow{}
	for rows.Next() {
		var i ClaimDueOutboxEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.AggregateType,
			&i.AggregateID,
			&i.Payload,
			&i.Attempts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createInvoice = `-- name: CreateInvoice :exec

INSERT INTO invoices (
  id, invoice_no, user_id, subscription_id, order_id, status, amount_minor, currency, due_at, paid_at
) VALUES ($1, $2, $3, NULL, $4, $5, $6, $7, NULL, NULL)
`

type CreateInvoiceParams struct {
	ID          uuid.UUID  `json:"id"`
	InvoiceNo   string     `json:"invoice_no"`
	UserID      uuid.UUID  `json:"user_id"`
	OrderID     *uuid.UUID `json:"order_id"`
	Status      string     `json:"status"`
	AmountMinor int64      `json:"amount_minor"`
	Currency    string     `json:"currency"`
}

// ---------------------------------------------------------------- invoices --
// An invoice is opened with the order, so it can say what was asked for before it was
// paid. `subscription_id` is left null: this phase's invoices arise from orders, and the
// renewal invoices of Phase 3 will set it instead.
func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) error {
	_, err := q.db.Exec(ctx, createInvoice,
		arg.ID,
		arg.InvoiceNo,
		arg.UserID,
		arg.OrderID,
		arg.Status,
		arg.AmountMinor,
		arg.Currency,
	)
	return err
}

const createInvoiceItem = `-- name: CreateInvoiceItem :exec
INSERT INTO invoice_items (id, invoice_id, description_i18n, quantity, unit_amount_minor, total_minor)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateInvoiceItemParams struct {
	ID              uuid.UUID `json:"id"`
	InvoiceID       uuid.UUID `json:"invoice_id"`
	DescriptionI18n []byte    `json:"description_i18n"`
	Quantity        int32     `json:"quantity"`
	UnitAmountMinor int64     `json:"unit_amount_minor"`
	TotalMinor      int64     `json:"total_minor"`
}

func (q *Queries) CreateInvoiceItem(ctx context.Context, arg CreateInvoiceItemParams) error {
	_, err := q.db.Exec(ctx, createInvoiceItem,
		arg.ID,
		arg.InvoiceID,
		arg.DescriptionI18n,
		arg.Quantity,
		arg.UnitAmountMinor,
		arg.TotalMinor,
	)
	return err
}

const createLedgerEntry = `-- name: CreateLedgerEntry :exec
INSERT INTO ledger_entries (id, transaction_id, account_type, account_id, direction, amount_minor, currency)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateLedgerEntryParams struct {
	ID            uuid.UUID `json:"id"`
	TransactionID uuid.UUID `json:"transaction_id"`
	AccountType   string    `json:"account_type"`
	AccountID     uuid.UUID `json:"account_id"`
	Direction     string    `json:"direction"`
	AmountMinor   int64     `json:"amount_minor"`
	Currency      string    `json:"currency"`
}

func (q *Queries) CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) error {
	_, err := q.db.Exec(ctx, createLedgerEntry,
		arg.ID,
		arg.TransactionID,
		arg.AccountType,
		arg.AccountID,
		arg.Direction,
		arg.AmountMinor,
		arg.Currency,
	)
	return err
}

const createLedgerTransaction = `-- name: CreateLedgerTransaction :exec

INSERT INTO ledger_transactions (id, type, reference_type, reference_id, description)
VALUES ($1, $2, $3, $4, $5)
`

type CreateLedgerTransactionParams struct {
	ID            uuid.UUID   `json:"id"`
	Type          string      `json:"type"`
	ReferenceType pgtype.Text `json:"reference_type"`
	ReferenceID   *uuid.UUID  `json:"reference_id"`
	Description   pgtype.Text `json:"description"`
}

// ------------------------------------------------------------------ ledger --
func (q *Queries) CreateLedgerTransaction(ctx context.Context, arg CreateLedgerTransactionParams) error {
	_, err := q.db.Exec(ctx, createLedgerTransaction,
		arg.ID,
		arg.Type,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.Description,
	)
	return err
}

const createOrder = `-- name: CreateOrder :exec

INSERT INTO orders (
  id, order_no, user_id, status,
  subtotal_minor, discount_minor, total_minor, currency, paid_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateOrderParams struct {
	ID            uuid.UUID          `json:"id"`
	OrderNo       string             `json:"order_no"`
	UserID        uuid.UUID          `json:"user_id"`
	Status        string             `json:"status"`
	SubtotalMinor int64              `json:"subtotal_minor"`
	DiscountMinor int64              `json:"discount_minor"`
	TotalMinor    int64              `json:"total_minor"`
	Currency      string             `json:"currency"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
}

// ------------------------------------------------------------------ orders --
func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) error {
	_, err := q.db.Exec(ctx, createOrder,
		arg.ID,
		arg.OrderNo,
		arg.UserID,
		arg.Status,
		arg.SubtotalMinor,
		arg.DiscountMinor,
		arg.TotalMinor,
		arg.Currency,
		arg.PaidAt,
	)
	return err
}

const createOrderItem = `-- name: CreateOrderItem :exec
INSERT INTO order_items (
  id, order_id, product_id, plan_id, quantity,
  unit_price_minor, total_minor, product_snapshot, plan_snapshot
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateOrderItemParams struct {
	ID              uuid.UUID `json:"id"`
	OrderID         uuid.UUID `json:"order_id"`
	ProductID       uuid.UUID `json:"product_id"`
	PlanID          uuid.UUID `json:"plan_id"`
	Quantity        int32     `json:"quantity"`
	UnitPriceMinor  int64     `json:"unit_price_minor"`
	TotalMinor      int64     `json:"total_minor"`
	ProductSnapshot []byte    `json:"product_snapshot"`
	PlanSnapshot    []byte    `json:"plan_snapshot"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error {
	_, err := q.db.Exec(ctx, createOrderItem,
		arg.ID,
		arg.OrderID,
		arg.ProductID,
		arg.PlanID,
		arg.Quantity,
		arg.UnitPriceMinor,
		arg.TotalMinor,
		arg.ProductSnapshot,
		arg.PlanSnapshot,
	)
	return err
}

const createOutboxEvent = `-- name: CreateOutboxEvent :exec

INSERT INTO outbox_events (id, event_type, aggregate_type, aggregate_id, payload)
VALUES ($1, $2, $3, $4, $5)
`

type CreateOutboxEventParams struct {
	ID            uuid.UUID `json:"id"`
	EventType     string    `json:"event_type"`
	AggregateType string    `json:"aggregate_type"`
	AggregateID   uuid.UUID `json:"aggregate_id"`
	Payload       []byte    `json:"payload"`
}

// ------------------------------------------------------------------- outbox --
// Written in the same transaction as the change it describes (docs/09). Publishing is
// the worker's, in Phase 5.
func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) error {
	_, err := q.db.Exec(ctx, createOutboxEvent,
		arg.ID,
		arg.EventType,
		arg.AggregateType,
		arg.AggregateID,
		arg.Payload,
	)
	return err
}

const createPayment = `-- name: CreatePayment :exec

INSERT INTO payments (
  id, payment_no, order_id, gateway, gateway_payment_id, status,
  amount_minor, currency, idempotency_key, gateway_payload, paid_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, '{}'::jsonb, NULL)
`

type CreatePaymentParams struct {
	ID               uuid.UUID   `json:"id"`
	PaymentNo        string      `json:"payment_no"`
	OrderID          uuid.UUID   `json:"order_id"`
	Gateway          string      `json:"gateway"`
	GatewayPaymentID pgtype.Text `json:"gateway_payment_id"`
	Status           string      `json:"status"`
	AmountMinor      int64       `json:"amount_minor"`
	Currency         string      `json:"currency"`
	IdempotencyKey   string      `json:"idempotency_key"`
}

// ---------------------------------------------------------------- payments --
func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) error {
	_, err := q.db.Exec(ctx, createPayment,
		arg.ID,
		arg.PaymentNo,
		arg.OrderID,
		arg.Gateway,
		arg.GatewayPaymentID,
		arg.Status,
		arg.AmountMinor,
		arg.Currency,
		arg.IdempotencyKey,
	)
	return err
}

const failPayment = `-- name: FailPayment :one
UPDATE payments
SET status = 'failed', updated_at = $2
WHERE id = $1 AND status IN ('pending', 'processing')
RETURNING id, payment_no, order_id, gateway, gateway_payment_id, status, amount_minor,
          currency, idempotency_key, gateway_payload, paid_at, created_at, updated_at
`

type FailPaymentParams struct {
	ID        uuid.UUID          `json:"id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) FailPayment(ctx context.Context, arg FailPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, failPayment, arg.ID, arg.UpdatedAt)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.PaymentNo,
		&i.OrderID,
		&i.Gateway,
		&i.GatewayPaymentID,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.IdempotencyKey,
		&i.GatewayPayload,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivePlans = `-- name: ListActivePlans :many
SELECT id, product_id, node_group_id, slug, name_i18n, status, memory_mb, disk_gb,
       traffic_gb, bandwidth_mbps, ipv4_count, ipv6_count, nat_port_count, virtualization,
       billing_cycle, price_minor, currency, stock_mode, created_at, updated_at,
       cpu_cores::text AS cpu_cores_text
FROM plans
WHERE status = 'active'
ORDER BY price_minor, slug
`

type ListActivePlansRow struct {
	ID             uuid.UUID          `json:"id"`
	ProductID      uuid.UUID          `json:"product_id"`
	NodeGroupID    *uuid.UUID         `json:"node_group_id"`
	Slug           string             `json:"slug"`
	NameI18n       []byte             `json:"name_i18n"`
	Status         string             `json:"status"`
	MemoryMb       int32              `json:"memory_mb"`
	DiskGb         int32              `json:"disk_gb"`
	TrafficGb      pgtype.Int8        `json:"traffic_gb"`
	BandwidthMbps  pgtype.Int4        `json:"bandwidth_mbps"`
	Ipv4Count      int32              `json:"ipv4_count"`
	Ipv6Count      int32              `json:"ipv6_count"`
	NatPortCount   int32              `json:"nat_port_count"`
	Virtualization string             `json:"virtualization"`
	BillingCycle   string             `json:"billing_cycle"`
	PriceMinor     int64              `json:"price_minor"`
	Currency       string             `json:"currency"`
	StockMode      string             `json:"stock_mode"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CpuCoresText   string             `json:"cpu_cores_text"`
}

func (q *Queries) ListActivePlans(ctx context.Context) ([]ListActivePlansRow, error) {
	rows, err := q.db.Query(ctx, listActivePlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivePlansRow{}
	for rows.Next() {
		var i ListActivePlansRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.NodeGroupID,
			&i.Slug,
			&i.NameI18n,
			&i.Status,
			&i.MemoryMb,
			&i.DiskGb,
			&i.TrafficGb,
			&i.BandwidthMbps,
			&i.Ipv4Count,
			&i.Ipv6Count,
			&i.NatPortCount,
			&i.Virtualization,
			&i.BillingCycle,
			&i.PriceMinor,
			&i.Currency,
			&i.StockMode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CpuCoresText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveProducts = `-- name: ListActiveProducts :many


SELECT id, slug, name_i18n, description_i18n, status, sort_order, created_at, updated_at
FROM products
WHERE status = 'active'
ORDER BY sort_order, slug
`

// The commercial queries.
//
// Every statement is written to be safe to run inside the transaction the settlement
// uses, and the two state transitions are conditional updates: the WHERE clause names
// the state the row must be in, so exactly one caller of a hundred can see a row
// returned. That is the property the Gate is about, and it is a property of the
// statement rather than of the code around it.
// ---------------------------------------------------------------- catalogue --
func (q *Queries) ListActiveProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listActiveProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.NameI18n,
			&i.DescriptionI18n,
			&i.Status,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersForUser = `-- name: ListOrdersForUser :many
SELECT id, order_no, user_id, status, subtotal_minor, discount_minor, total_minor,
       currency, paid_at, created_at, updated_at
FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 100
`

func (q *Queries) ListOrdersForUser(ctx context.Context, userID uuid.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OrderNo,
			&i.UserID,
			&i.Status,
			&i.SubtotalMinor,
			&i.DiscountMinor,
			&i.TotalMinor,
			&i.Currency,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInvoicePaid = `-- name: MarkInvoicePaid :execrows
UPDATE invoices
SET status = 'paid', paid_at = $2, updated_at = $2
WHERE order_id = $1 AND status = 'open'
`

type MarkInvoicePaidParams struct {
	OrderID *uuid.UUID         `json:"order_id"`
	PaidAt  pgtype.Timestamptz `json:"paid_at"`
}

func (q *Queries) MarkInvoicePaid(ctx context.Context, arg MarkInvoicePaidParams) (int64, error) {
	result, err := q.db.Exec(ctx, markInvoicePaid, arg.OrderID, arg.PaidAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOutboxFailed = `-- name: MarkOutboxFailed :execrows
UPDATE outbox_events
SET status = 'pending', next_attempt_at = $2
WHERE id = $1 AND status = 'pending'
`

type MarkOutboxFailedParams struct {
	ID            uuid.UUID          `json:"id"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
}

// A failed delivery retries on the same backoff the operations use.
func (q *Queries) MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOutboxFailed, arg.ID, arg.NextAttemptAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOutboxPublished = `-- name: MarkOutboxPublished :execrows
UPDATE outbox_events
SET status = 'published', published_at = $2
WHERE id = $1
`

type MarkOutboxPublishedParams struct {
	ID          uuid.UUID          `json:"id"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

// A delivered event leaves the queue for good; consumer dedup is by event_id.
func (q *Queries) MarkOutboxPublished(ctx context.Context, arg MarkOutboxPublishedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOutboxPublished, arg.ID, arg.PublishedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const orderByIDForUser = `-- name: OrderByIDForUser :one
SELECT id, order_no, user_id, status, subtotal_minor, discount_minor, total_minor,
       currency, paid_at, created_at, updated_at
FROM orders
WHERE id = $1 AND user_id = $2
`

type OrderByIDForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) OrderByIDForUser(ctx context.Context, arg OrderByIDForUserParams) (Order, error) {
	row := q.db.QueryRow(ctx, orderByIDForUser, arg.ID, arg.UserID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.UserID,
		&i.Status,
		&i.SubtotalMinor,
		&i.DiscountMinor,
		&i.TotalMinor,
		&i.Currency,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const orderItemsForOrder = `-- name: OrderItemsForOrder :many
SELECT id, order_id, product_id, plan_id, quantity, unit_price_minor, total_minor,
       product_snapshot, plan_snapshot, created_at
FROM order_items
WHERE order_id = $1
ORDER BY created_at, id
`

func (q *Queries) OrderItemsForOrder(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, orderItemsForOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.PlanID,
			&i.Quantity,
			&i.UnitPriceMinor,
			&i.TotalMinor,
			&i.ProductSnapshot,
			&i.PlanSnapshot,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const payOrder = `-- name: PayOrder :execrows
UPDATE orders
SET status = 'paid', paid_at = $2, updated_at = $2
WHERE id = $1 AND status = 'pending'
`

type PayOrderParams struct {
	ID     uuid.UUID          `json:"id"`
	PaidAt pgtype.Timestamptz `json:"paid_at"`
}

// The condition names the only state a payment can settle from. A row that is not
// pending is either already paid — a redelivered callback — or cancelled, and neither
// may be moved by a second writer.
func (q *Queries) PayOrder(ctx context.Context, arg PayOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, payOrder, arg.ID, arg.PaidAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const paymentByGatewayRef = `-- name: PaymentByGatewayRef :one
SELECT id, payment_no, order_id, gateway, gateway_payment_id, status, amount_minor,
       currency, idempotency_key, gateway_payload, paid_at, created_at, updated_at
FROM payments
WHERE gateway = $1 AND gateway_payment_id = $2
`

type PaymentByGatewayRefParams struct {
	Gateway          string      `json:"gateway"`
	GatewayPaymentID pgtype.Text `json:"gateway_payment_id"`
}

func (q *Queries) PaymentByGatewayRef(ctx context.Context, arg PaymentByGatewayRefParams) (Payment, error) {
	row := q.db.QueryRow(ctx, paymentByGatewayRef, arg.Gateway, arg.GatewayPaymentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.PaymentNo,
		&i.OrderID,
		&i.Gateway,
		&i.GatewayPaymentID,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.IdempotencyKey,
		&i.GatewayPayload,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const planByID = `-- name: PlanByID :one
SELECT id, product_id, node_group_id, slug, name_i18n, status, memory_mb, disk_gb,
       traffic_gb, bandwidth_mbps, ipv4_count, ipv6_count, nat_port_count, virtualization,
       billing_cycle, price_minor, currency, stock_mode, created_at, updated_at,
       cpu_cores::text AS cpu_cores_text
FROM plans
WHERE id = $1
`

type PlanByIDRow struct {
	ID             uuid.UUID          `json:"id"`
	ProductID      uuid.UUID          `json:"product_id"`
	NodeGroupID    *uuid.UUID         `json:"node_group_id"`
	Slug           string             `json:"slug"`
	NameI18n       []byte             `json:"name_i18n"`
	Status         string             `json:"status"`
	MemoryMb       int32              `json:"memory_mb"`
	DiskGb         int32              `json:"disk_gb"`
	TrafficGb      pgtype.Int8        `json:"traffic_gb"`
	BandwidthMbps  pgtype.Int4        `json:"bandwidth_mbps"`
	Ipv4Count      int32              `json:"ipv4_count"`
	Ipv6Count      int32              `json:"ipv6_count"`
	NatPortCount   int32              `json:"nat_port_count"`
	Virtualization string             `json:"virtualization"`
	BillingCycle   string             `json:"billing_cycle"`
	PriceMinor     int64              `json:"price_minor"`
	Currency       string             `json:"currency"`
	StockMode      string             `json:"stock_mode"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CpuCoresText   string             `json:"cpu_cores_text"`
}

func (q *Queries) PlanByID(ctx context.Context, id uuid.UUID) (PlanByIDRow, error) {
	row := q.db.QueryRow(ctx, planByID, id)
	var i PlanByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.NodeGroupID,
		&i.Slug,
		&i.NameI18n,
		&i.Status,
		&i.MemoryMb,
		&i.DiskGb,
		&i.TrafficGb,
		&i.BandwidthMbps,
		&i.Ipv4Count,
		&i.Ipv6Count,
		&i.NatPortCount,
		&i.Virtualization,
		&i.BillingCycle,
		&i.PriceMinor,
		&i.Currency,
		&i.StockMode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CpuCoresText,
	)
	return i, err
}

const settlePayment = `-- name: SettlePayment :one
UPDATE payments
SET status = 'succeeded', paid_at = $2, updated_at = $2
WHERE id = $1 AND status IN ('pending', 'processing')
RETURNING id, payment_no, order_id, gateway, gateway_payment_id, status, amount_minor,
          currency, idempotency_key, gateway_payload, paid_at, created_at, updated_at
`

type SettlePaymentParams struct {
	ID     uuid.UUID          `json:"id"`
	PaidAt pgtype.Timestamptz `json:"paid_at"`
}

// The whole idempotency decision is this statement. It is one UPDATE with the current
// state named in the WHERE clause, so under a hundred concurrent deliveries of the same
// callback exactly one of them returns a row and the other ninety-nine see none.
func (q *Queries) SettlePayment(ctx context.Context, arg SettlePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, settlePayment, arg.ID, arg.PaidAt)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.PaymentNo,
		&i.OrderID,
		&i.Gateway,
		&i.GatewayPaymentID,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.IdempotencyKey,
		&i.GatewayPayload,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sumLedgerAccount = `-- name: SumLedgerAccount :one
SELECT COALESCE(
         SUM(CASE WHEN direction = 'credit' THEN amount_minor ELSE - amount_minor END),
         0
       )::bigint AS balance
FROM ledger_entries
WHERE account_type = $1 AND account_id = $2 AND currency = $3
`

type SumLedgerAccountParams struct {
	AccountType string    `json:"account_type"`
	AccountID   uuid.UUID `json:"account_id"`
	Currency    string    `json:"currency"`
}

// The credit-minus-debit total of one account. This is the derivation the wallet
// projection is checked against (ADR-005): it reads the entries and nothing else, so it
// is the answer to "is the projection right".
func (q *Queries) SumLedgerAccount(ctx context.Context, arg SumLedgerAccountParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumLedgerAccount, arg.AccountType, arg.AccountID, arg.Currency)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const upsertWalletBalance = `-- name: UpsertWalletBalance :exec
INSERT INTO wallets (id, user_id, currency, available_balance_minor)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, currency) DO UPDATE
SET available_balance_minor = wallets.available_balance_minor + $4,
    updated_at = now()
`

type UpsertWalletBalanceParams struct {
	ID                    uuid.UUID `json:"id"`
	UserID                uuid.UUID `json:"user_id"`
	Currency              string    `json:"currency"`
	AvailableBalanceMinor int64     `json:"available_balance_minor"`
}

// The projection. Applied in the same transaction as the entries it summarises, and
// always as a delta rather than an absolute value, because an absolute write would
// silently overwrite whatever a concurrent posting had already added.
func (q *Queries) UpsertWalletBalance(ctx context.Context, arg UpsertWalletBalanceParams) error {
	_, err := q.db.Exec(ctx, upsertWalletBalance,
		arg.ID,
		arg.UserID,
		arg.Currency,
		arg.AvailableBalanceMinor,
	)
	return err
}
