// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package sqlcgen

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminTwoFactorByAdmin = `-- name: AdminTwoFactorByAdmin :one
SELECT id, two_factor_secret, two_factor_enabled FROM admins WHERE id = $1
`

type AdminTwoFactorByAdminRow struct {
	ID               uuid.UUID   `json:"id"`
	TwoFactorSecret  pgtype.Text `json:"two_factor_secret"`
	TwoFactorEnabled bool        `json:"two_factor_enabled"`
}

func (q *Queries) AdminTwoFactorByAdmin(ctx context.Context, id uuid.UUID) (AdminTwoFactorByAdminRow, error) {
	row := q.db.QueryRow(ctx, adminTwoFactorByAdmin, id)
	var i AdminTwoFactorByAdminRow
	err := row.Scan(&i.ID, &i.TwoFactorSecret, &i.TwoFactorEnabled)
	return i, err
}

const adminTwoFactorEmail = `-- name: AdminTwoFactorEmail :one
SELECT email FROM admins WHERE id = $1
`

func (q *Queries) AdminTwoFactorEmail(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, adminTwoFactorEmail, id)
	var email string
	err := row.Scan(&email)
	return email, err
}

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admins (
  id, email, password_hash, status, display_name
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, email, password_hash, status, display_name, two_factor_enabled, last_login_at, created_at, updated_at, two_factor_secret
`

type CreateAdminParams struct {
	ID           uuid.UUID   `json:"id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Status       string      `json:"status"`
	DisplayName  pgtype.Text `json:"display_name"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error) {
	row := q.db.QueryRow(ctx, createAdmin,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Status,
		arg.DisplayName,
	)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.DisplayName,
		&i.TwoFactorEnabled,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TwoFactorSecret,
	)
	return i, err
}

const createAuditEvent = `-- name: CreateAuditEvent :exec
INSERT INTO audit_events (
  id, actor_type, actor_id, action, resource_type, resource_id,
  before_data, after_data, ip_address, user_agent, request_id, trace_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
`

type CreateAuditEventParams struct {
	ID           uuid.UUID   `json:"id"`
	ActorType    string      `json:"actor_type"`
	ActorID      *uuid.UUID  `json:"actor_id"`
	Action       string      `json:"action"`
	ResourceType string      `json:"resource_type"`
	ResourceID   *uuid.UUID  `json:"resource_id"`
	BeforeData   []byte      `json:"before_data"`
	AfterData    []byte      `json:"after_data"`
	IpAddress    *netip.Addr `json:"ip_address"`
	UserAgent    pgtype.Text `json:"user_agent"`
	RequestID    pgtype.Text `json:"request_id"`
	TraceID      pgtype.Text `json:"trace_id"`
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error {
	_, err := q.db.Exec(ctx, createAuditEvent,
		arg.ID,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.BeforeData,
		arg.AfterData,
		arg.IpAddress,
		arg.UserAgent,
		arg.RequestID,
		arg.TraceID,
	)
	return err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (
  id, email, password_hash, status, locale, timezone
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, email, password_hash, status, locale, timezone, email_verified_at, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Status       string    `json:"status"`
	Locale       string    `json:"locale"`
	Timezone     string    `json:"timezone"`
}

// Identity queries for Phase 1.
//
// These are the only statements that read or write credentials. Nothing outside
// this file touches `users.password_hash` or `admins.password_hash`, so the hash
// has one reader (the login path) and one writer (registration and any future
// password change), which is what keeps the verification logic from drifting.
//
// Email is compared against the stored value after the application has normalised
// it (trimmed and lower-cased). Normalising in SQL as well would make every lookup
// non-sargable for no benefit, since the write path is the only writer.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Status,
		arg.Locale,
		arg.Timezone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.Locale,
		&i.Timezone,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminByEmail = `-- name: GetAdminByEmail :one
SELECT id, email, password_hash, status, display_name, two_factor_enabled, last_login_at, created_at, updated_at, two_factor_secret FROM admins WHERE email = $1
`

func (q *Queries) GetAdminByEmail(ctx context.Context, email string) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByEmail, email)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.DisplayName,
		&i.TwoFactorEnabled,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TwoFactorSecret,
	)
	return i, err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, email, password_hash, status, display_name, two_factor_enabled, last_login_at, created_at, updated_at, two_factor_secret FROM admins WHERE id = $1
`

func (q *Queries) GetAdminByID(ctx context.Context, id uuid.UUID) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByID, id)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.DisplayName,
		&i.TwoFactorEnabled,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TwoFactorSecret,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, status, locale, timezone, email_verified_at, last_login_at, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.Locale,
		&i.Timezone,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, status, locale, timezone, email_verified_at, last_login_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.Locale,
		&i.Timezone,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPermissionKeys = `-- name: ListPermissionKeys :many
SELECT key FROM permissions ORDER BY key
`

func (q *Queries) ListPermissionKeys(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listPermissionKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsForAdmin = `-- name: ListPermissionsForAdmin :many
SELECT DISTINCT p.key
FROM admin_roles ar
JOIN role_permissions rp ON rp.role_id = ar.role_id
JOIN permissions p ON p.id = rp.permission_id
WHERE ar.admin_id = $1
ORDER BY p.key
`

// The effective permission set is resolved from the database on each request
// rather than cached in the session, so revoking a role takes effect immediately
// instead of at the next login.
func (q *Queries) ListPermissionsForAdmin(ctx context.Context, adminID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listPermissionsForAdmin, adminID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesForAdmin = `-- name: ListRolesForAdmin :many
SELECT r.key
FROM admin_roles ar
JOIN roles r ON r.id = ar.role_id
WHERE ar.admin_id = $1
ORDER BY r.key
`

func (q *Queries) ListRolesForAdmin(ctx context.Context, adminID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listRolesForAdmin, adminID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAdminLogin = `-- name: RecordAdminLogin :exec
UPDATE admins
SET last_login_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) RecordAdminLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, recordAdminLogin, id)
	return err
}

const recordUserLogin = `-- name: RecordUserLogin :exec
UPDATE users
SET last_login_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) RecordUserLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, recordUserLogin, id)
	return err
}

const setAdminTwoFactor = `-- name: SetAdminTwoFactor :execrows
UPDATE admins
SET two_factor_secret = $2, two_factor_enabled = $3, updated_at = $4
WHERE id = $1
`

type SetAdminTwoFactorParams struct {
	ID               uuid.UUID          `json:"id"`
	TwoFactorSecret  pgtype.Text        `json:"two_factor_secret"`
	TwoFactorEnabled bool               `json:"two_factor_enabled"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

// The TOTP enrollment (ADR-015 §1): secret and flag move in one write, and
// the enable path verifies a code before the flag flips.
func (q *Queries) SetAdminTwoFactor(ctx context.Context, arg SetAdminTwoFactorParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAdminTwoFactor,
		arg.ID,
		arg.TwoFactorSecret,
		arg.TwoFactorEnabled,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAdminPasswordHash = `-- name: UpdateAdminPasswordHash :exec
UPDATE admins
SET password_hash = $2, updated_at = now()
WHERE id = $1
`

type UpdateAdminPasswordHashParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateAdminPasswordHash(ctx context.Context, arg UpdateAdminPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateAdminPasswordHash, arg.ID, arg.PasswordHash)
	return err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :exec
UPDATE users
SET password_hash = $2, updated_at = now()
WHERE id = $1
`

type UpdateUserPasswordHashParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

// Replacing the hash is how a raised argon2 cost is applied. It only ever happens
// on a successful login, which is the only moment the plaintext exists.
func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordHash, arg.ID, arg.PasswordHash)
	return err
}
