// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: infra.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const commitNodeResources = `-- name: CommitNodeResources :execrows
UPDATE nodes
SET cpu_allocated = cpu_allocated + $2::numeric,
    memory_allocated_mb = memory_allocated_mb + $3,
    disk_allocated_gb = disk_allocated_gb + $4,
    cpu_reserved = cpu_reserved - $2::numeric,
    memory_reserved_mb = memory_reserved_mb - $3,
    disk_reserved_gb = disk_reserved_gb - $4,
    version = version + 1, updated_at = $5
WHERE id = $1
`

type CommitNodeResourcesParams struct {
	ID                uuid.UUID          `json:"id"`
	Column2           pgtype.Numeric     `json:"column_2"`
	MemoryAllocatedMb int64              `json:"memory_allocated_mb"`
	DiskAllocatedGb   int64              `json:"disk_allocated_gb"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

// The commit: the promise becomes an allocation, in the transaction that
// records the instance it bought. Unconditional on the counters because the
// reservation that reached here was already gated; a commit for a reservation
// that was never made is a caller bug this cannot fix.
func (q *Queries) CommitNodeResources(ctx context.Context, arg CommitNodeResourcesParams) (int64, error) {
	result, err := q.db.Exec(ctx, commitNodeResources,
		arg.ID,
		arg.Column2,
		arg.MemoryAllocatedMb,
		arg.DiskAllocatedGb,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listNodeGroups = `-- name: ListNodeGroups :many
SELECT id, name, region, status, created_at, updated_at
FROM node_groups
ORDER BY name
`

func (q *Queries) ListNodeGroups(ctx context.Context) ([]NodeGroup, error) {
	rows, err := q.db.Query(ctx, listNodeGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeGroup{}
	for rows.Next() {
		var i NodeGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Region,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodes = `-- name: ListNodes :many
SELECT id, provider_id, node_group_id, provider_node_id, name, region, status,
       cpu_total::text AS cpu_total_text, memory_total_mb, disk_total_gb,
       cpu_allocated::text AS cpu_allocated_text, memory_allocated_mb, disk_allocated_gb,
       cpu_reserved::text AS cpu_reserved_text, memory_reserved_mb, disk_reserved_gb,
       weight, capabilities, last_seen_at, version, created_at, updated_at
FROM nodes
ORDER BY name
`

type ListNodesRow struct {
	ID                uuid.UUID          `json:"id"`
	ProviderID        uuid.UUID          `json:"provider_id"`
	NodeGroupID       *uuid.UUID         `json:"node_group_id"`
	ProviderNodeID    pgtype.Text        `json:"provider_node_id"`
	Name              string             `json:"name"`
	Region            string             `json:"region"`
	Status            string             `json:"status"`
	CpuTotalText      string             `json:"cpu_total_text"`
	MemoryTotalMb     int64              `json:"memory_total_mb"`
	DiskTotalGb       int64              `json:"disk_total_gb"`
	CpuAllocatedText  string             `json:"cpu_allocated_text"`
	MemoryAllocatedMb int64              `json:"memory_allocated_mb"`
	DiskAllocatedGb   int64              `json:"disk_allocated_gb"`
	CpuReservedText   string             `json:"cpu_reserved_text"`
	MemoryReservedMb  int64              `json:"memory_reserved_mb"`
	DiskReservedGb    int64              `json:"disk_reserved_gb"`
	Weight            int32              `json:"weight"`
	Capabilities      []byte             `json:"capabilities"`
	LastSeenAt        pgtype.Timestamptz `json:"last_seen_at"`
	Version           int64              `json:"version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListNodes(ctx context.Context) ([]ListNodesRow, error) {
	rows, err := q.db.Query(ctx, listNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNodesRow{}
	for rows.Next() {
		var i ListNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.NodeGroupID,
			&i.ProviderNodeID,
			&i.Name,
			&i.Region,
			&i.Status,
			&i.CpuTotalText,
			&i.MemoryTotalMb,
			&i.DiskTotalGb,
			&i.CpuAllocatedText,
			&i.MemoryAllocatedMb,
			&i.DiskAllocatedGb,
			&i.CpuReservedText,
			&i.MemoryReservedMb,
			&i.DiskReservedGb,
			&i.Weight,
			&i.Capabilities,
			&i.LastSeenAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviders = `-- name: ListProviders :many


SELECT id, name, provider_type, endpoint, credential_ref, status, version,
       config, capabilities, last_health_check_at, created_at, updated_at
FROM providers
ORDER BY name
`

// The infrastructure queries.
//
// The reservation transitions are conditional updates for the same reason every
// other writer here is: repetition and concurrency are the normal case, and the
// row's own counters are the gate.
// ------------------------------------------------------------------- reads --
func (q *Queries) ListProviders(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProviderType,
			&i.Endpoint,
			&i.CredentialRef,
			&i.Status,
			&i.Version,
			&i.Config,
			&i.Capabilities,
			&i.LastHealthCheckAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nodeByID = `-- name: NodeByID :one
SELECT id, provider_id, node_group_id, provider_node_id, name, region, status,
       cpu_total::text AS cpu_total_text, memory_total_mb, disk_total_gb,
       cpu_allocated::text AS cpu_allocated_text, memory_allocated_mb, disk_allocated_gb,
       cpu_reserved::text AS cpu_reserved_text, memory_reserved_mb, disk_reserved_gb,
       weight, capabilities, last_seen_at, version, created_at, updated_at
FROM nodes
WHERE id = $1
`

type NodeByIDRow struct {
	ID                uuid.UUID          `json:"id"`
	ProviderID        uuid.UUID          `json:"provider_id"`
	NodeGroupID       *uuid.UUID         `json:"node_group_id"`
	ProviderNodeID    pgtype.Text        `json:"provider_node_id"`
	Name              string             `json:"name"`
	Region            string             `json:"region"`
	Status            string             `json:"status"`
	CpuTotalText      string             `json:"cpu_total_text"`
	MemoryTotalMb     int64              `json:"memory_total_mb"`
	DiskTotalGb       int64              `json:"disk_total_gb"`
	CpuAllocatedText  string             `json:"cpu_allocated_text"`
	MemoryAllocatedMb int64              `json:"memory_allocated_mb"`
	DiskAllocatedGb   int64              `json:"disk_allocated_gb"`
	CpuReservedText   string             `json:"cpu_reserved_text"`
	MemoryReservedMb  int64              `json:"memory_reserved_mb"`
	DiskReservedGb    int64              `json:"disk_reserved_gb"`
	Weight            int32              `json:"weight"`
	Capabilities      []byte             `json:"capabilities"`
	LastSeenAt        pgtype.Timestamptz `json:"last_seen_at"`
	Version           int64              `json:"version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) NodeByID(ctx context.Context, id uuid.UUID) (NodeByIDRow, error) {
	row := q.db.QueryRow(ctx, nodeByID, id)
	var i NodeByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.NodeGroupID,
		&i.ProviderNodeID,
		&i.Name,
		&i.Region,
		&i.Status,
		&i.CpuTotalText,
		&i.MemoryTotalMb,
		&i.DiskTotalGb,
		&i.CpuAllocatedText,
		&i.MemoryAllocatedMb,
		&i.DiskAllocatedGb,
		&i.CpuReservedText,
		&i.MemoryReservedMb,
		&i.DiskReservedGb,
		&i.Weight,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const nodesForGroup = `-- name: NodesForGroup :many
SELECT id, provider_id, node_group_id, provider_node_id, name, region, status,
       cpu_total::text AS cpu_total_text, memory_total_mb, disk_total_gb,
       cpu_allocated::text AS cpu_allocated_text, memory_allocated_mb, disk_allocated_gb,
       cpu_reserved::text AS cpu_reserved_text, memory_reserved_mb, disk_reserved_gb,
       weight, capabilities, last_seen_at, version, created_at, updated_at
FROM nodes
WHERE node_group_id = $1 AND status = 'online'
ORDER BY id
`

type NodesForGroupRow struct {
	ID                uuid.UUID          `json:"id"`
	ProviderID        uuid.UUID          `json:"provider_id"`
	NodeGroupID       *uuid.UUID         `json:"node_group_id"`
	ProviderNodeID    pgtype.Text        `json:"provider_node_id"`
	Name              string             `json:"name"`
	Region            string             `json:"region"`
	Status            string             `json:"status"`
	CpuTotalText      string             `json:"cpu_total_text"`
	MemoryTotalMb     int64              `json:"memory_total_mb"`
	DiskTotalGb       int64              `json:"disk_total_gb"`
	CpuAllocatedText  string             `json:"cpu_allocated_text"`
	MemoryAllocatedMb int64              `json:"memory_allocated_mb"`
	DiskAllocatedGb   int64              `json:"disk_allocated_gb"`
	CpuReservedText   string             `json:"cpu_reserved_text"`
	MemoryReservedMb  int64              `json:"memory_reserved_mb"`
	DiskReservedGb    int64              `json:"disk_reserved_gb"`
	Weight            int32              `json:"weight"`
	Capabilities      []byte             `json:"capabilities"`
	LastSeenAt        pgtype.Timestamptz `json:"last_seen_at"`
	Version           int64              `json:"version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) NodesForGroup(ctx context.Context, nodeGroupID *uuid.UUID) ([]NodesForGroupRow, error) {
	rows, err := q.db.Query(ctx, nodesForGroup, nodeGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodesForGroupRow{}
	for rows.Next() {
		var i NodesForGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.NodeGroupID,
			&i.ProviderNodeID,
			&i.Name,
			&i.Region,
			&i.Status,
			&i.CpuTotalText,
			&i.MemoryTotalMb,
			&i.DiskTotalGb,
			&i.CpuAllocatedText,
			&i.MemoryAllocatedMb,
			&i.DiskAllocatedGb,
			&i.CpuReservedText,
			&i.MemoryReservedMb,
			&i.DiskReservedGb,
			&i.Weight,
			&i.Capabilities,
			&i.LastSeenAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const providerByID = `-- name: ProviderByID :one
SELECT id, name, provider_type, endpoint, credential_ref, status, version,
       config, capabilities, last_health_check_at, created_at, updated_at
FROM providers
WHERE id = $1
`

func (q *Queries) ProviderByID(ctx context.Context, id uuid.UUID) (Provider, error) {
	row := q.db.QueryRow(ctx, providerByID, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProviderType,
		&i.Endpoint,
		&i.CredentialRef,
		&i.Status,
		&i.Version,
		&i.Config,
		&i.Capabilities,
		&i.LastHealthCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const releaseNodeResources = `-- name: ReleaseNodeResources :execrows
UPDATE nodes
SET cpu_reserved = cpu_reserved - $2::numeric,
    memory_reserved_mb = memory_reserved_mb - $3,
    disk_reserved_gb = disk_reserved_gb - $4,
    version = version + 1, updated_at = $5
WHERE id = $1
  AND cpu_reserved >= $2::numeric
  AND memory_reserved_mb >= $3
  AND disk_reserved_gb >= $4
`

type ReleaseNodeResourcesParams struct {
	ID               uuid.UUID          `json:"id"`
	Column2          pgtype.Numeric     `json:"column_2"`
	MemoryReservedMb int64              `json:"memory_reserved_mb"`
	DiskReservedGb   int64              `json:"disk_reserved_gb"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

// The release: the promise is withdrawn. Conditional on the counters holding
// the reservation, so a double release or a release after commit moves nothing
// rather than driving the counters negative.
func (q *Queries) ReleaseNodeResources(ctx context.Context, arg ReleaseNodeResourcesParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseNodeResources,
		arg.ID,
		arg.Column2,
		arg.MemoryReservedMb,
		arg.DiskReservedGb,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reserveNodeResources = `-- name: ReserveNodeResources :execrows

UPDATE nodes
SET cpu_reserved = cpu_reserved + $2::numeric,
    memory_reserved_mb = memory_reserved_mb + $3,
    disk_reserved_gb = disk_reserved_gb + $4,
    version = version + 1, updated_at = $5
WHERE id = $1 AND status = 'online'
  AND cpu_total - cpu_allocated - cpu_reserved >= $2::numeric
  AND memory_total_mb - memory_allocated_mb - memory_reserved_mb >= $3
  AND disk_total_gb - disk_allocated_gb - disk_reserved_gb >= $4
`

type ReserveNodeResourcesParams struct {
	ID               uuid.UUID          `json:"id"`
	Column2          pgtype.Numeric     `json:"column_2"`
	MemoryReservedMb int64              `json:"memory_reserved_mb"`
	DiskReservedGb   int64              `json:"disk_reserved_gb"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

// ------------------------------------------------------------ reservations --
// The reserve: one statement is the whole gate. The counters only move if the
// node's free capacity covers the spec as the row stands right now, so two
// concurrent reservations of the same last vCPU cannot both promise it — the
// loser sees no row and reports the shortage.
func (q *Queries) ReserveNodeResources(ctx context.Context, arg ReserveNodeResourcesParams) (int64, error) {
	result, err := q.db.Exec(ctx, reserveNodeResources,
		arg.ID,
		arg.Column2,
		arg.MemoryReservedMb,
		arg.DiskReservedGb,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
