// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instance.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInstance = `-- name: CreateInstance :exec

INSERT INTO instances (id, subscription_id, node_id, provider_id, provider_instance_id,
                       name, desired_state, observed_state, cpu_cores, memory_mb, disk_gb,
                       image_id, last_synced_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type CreateInstanceParams struct {
	ID                 uuid.UUID          `json:"id"`
	SubscriptionID     uuid.UUID          `json:"subscription_id"`
	NodeID             *uuid.UUID         `json:"node_id"`
	ProviderID         *uuid.UUID         `json:"provider_id"`
	ProviderInstanceID pgtype.Text        `json:"provider_instance_id"`
	Name               string             `json:"name"`
	DesiredState       string             `json:"desired_state"`
	ObservedState      string             `json:"observed_state"`
	CpuCores           pgtype.Numeric     `json:"cpu_cores"`
	MemoryMb           int32              `json:"memory_mb"`
	DiskGb             int32              `json:"disk_gb"`
	ImageID            pgtype.Text        `json:"image_id"`
	LastSyncedAt       pgtype.Timestamptz `json:"last_synced_at"`
}

// The instance domain's queries (ADR-009).
func (q *Queries) CreateInstance(ctx context.Context, arg CreateInstanceParams) error {
	_, err := q.db.Exec(ctx, createInstance,
		arg.ID,
		arg.SubscriptionID,
		arg.NodeID,
		arg.ProviderID,
		arg.ProviderInstanceID,
		arg.Name,
		arg.DesiredState,
		arg.ObservedState,
		arg.CpuCores,
		arg.MemoryMb,
		arg.DiskGb,
		arg.ImageID,
		arg.LastSyncedAt,
	)
	return err
}

const createNotification = `-- name: CreateNotification :exec
INSERT INTO notifications (id, user_id, admin_id, type, title_key, message_key, parameters, severity)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateNotificationParams struct {
	ID         uuid.UUID  `json:"id"`
	UserID     *uuid.UUID `json:"user_id"`
	AdminID    *uuid.UUID `json:"admin_id"`
	Type       string     `json:"type"`
	TitleKey   string     `json:"title_key"`
	MessageKey string     `json:"message_key"`
	Parameters []byte     `json:"parameters"`
	Severity   string     `json:"severity"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	_, err := q.db.Exec(ctx, createNotification,
		arg.ID,
		arg.UserID,
		arg.AdminID,
		arg.Type,
		arg.TitleKey,
		arg.MessageKey,
		arg.Parameters,
		arg.Severity,
	)
	return err
}

const instanceBySubscription = `-- name: InstanceBySubscription :one
SELECT id, subscription_id, node_id, provider_id, provider_instance_id, name, desired_state, observed_state, cpu_cores, memory_mb, disk_gb, traffic_limit_gb, bandwidth_mbps, image_id, primary_ipv4, primary_ipv6, last_synced_at, version, created_at, updated_at, deleted_at FROM instances WHERE subscription_id = $1
`

// The idempotent create's lookup: a retried provision finds its instance by
// the subscription that owns exactly one.
func (q *Queries) InstanceBySubscription(ctx context.Context, subscriptionID uuid.UUID) (Instance, error) {
	row := q.db.QueryRow(ctx, instanceBySubscription, subscriptionID)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.NodeID,
		&i.ProviderID,
		&i.ProviderInstanceID,
		&i.Name,
		&i.DesiredState,
		&i.ObservedState,
		&i.CpuCores,
		&i.MemoryMb,
		&i.DiskGb,
		&i.TrafficLimitGb,
		&i.BandwidthMbps,
		&i.ImageID,
		&i.PrimaryIpv4,
		&i.PrimaryIpv6,
		&i.LastSyncedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const instancesForUser = `-- name: InstancesForUser :many
SELECT i.id, i.subscription_id, i.node_id, i.provider_id, i.provider_instance_id, i.name, i.desired_state, i.observed_state, i.cpu_cores, i.memory_mb, i.disk_gb, i.traffic_limit_gb, i.bandwidth_mbps, i.image_id, i.primary_ipv4, i.primary_ipv6, i.last_synced_at, i.version, i.created_at, i.updated_at, i.deleted_at FROM instances i
JOIN subscriptions s ON s.id = i.subscription_id
WHERE s.user_id = $1 AND i.deleted_at IS NULL
ORDER BY i.created_at DESC
`

func (q *Queries) InstancesForUser(ctx context.Context, userID uuid.UUID) ([]Instance, error) {
	rows, err := q.db.Query(ctx, instancesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Instance{}
	for rows.Next() {
		var i Instance
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.NodeID,
			&i.ProviderID,
			&i.ProviderInstanceID,
			&i.Name,
			&i.DesiredState,
			&i.ObservedState,
			&i.CpuCores,
			&i.MemoryMb,
			&i.DiskGb,
			&i.TrafficLimitGb,
			&i.BandwidthMbps,
			&i.ImageID,
			&i.PrimaryIpv4,
			&i.PrimaryIpv6,
			&i.LastSyncedAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInstanceObserved = `-- name: MarkInstanceObserved :execrows
UPDATE instances
SET observed_state = $2, last_synced_at = $3, version = version + 1, updated_at = $3
WHERE id = $1
`

type MarkInstanceObservedParams struct {
	ID            uuid.UUID          `json:"id"`
	ObservedState string             `json:"observed_state"`
	LastSyncedAt  pgtype.Timestamptz `json:"last_synced_at"`
}

func (q *Queries) MarkInstanceObserved(ctx context.Context, arg MarkInstanceObservedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markInstanceObserved, arg.ID, arg.ObservedState, arg.LastSyncedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setInstanceProvisioned = `-- name: SetInstanceProvisioned :execrows
UPDATE instances
SET node_id = $2, provider_id = $3, provider_instance_id = $4,
    observed_state = 'running', last_synced_at = $5, version = version + 1, updated_at = $5
WHERE id = $1
`

type SetInstanceProvisionedParams struct {
	ID                 uuid.UUID          `json:"id"`
	NodeID             *uuid.UUID         `json:"node_id"`
	ProviderID         *uuid.UUID         `json:"provider_id"`
	ProviderInstanceID pgtype.Text        `json:"provider_instance_id"`
	LastSyncedAt       pgtype.Timestamptz `json:"last_synced_at"`
}

// The moment the provider confirms running: the node and the provider identity
// land together with the observed state, in the caller's transaction.
func (q *Queries) SetInstanceProvisioned(ctx context.Context, arg SetInstanceProvisionedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setInstanceProvisioned,
		arg.ID,
		arg.NodeID,
		arg.ProviderID,
		arg.ProviderInstanceID,
		arg.LastSyncedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
