// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Admin struct {
	ID               uuid.UUID          `json:"id"`
	Email            string             `json:"email"`
	PasswordHash     string             `json:"password_hash"`
	Status           string             `json:"status"`
	DisplayName      pgtype.Text        `json:"display_name"`
	TwoFactorEnabled bool               `json:"two_factor_enabled"`
	LastLoginAt      pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type AdminRole struct {
	AdminID uuid.UUID `json:"admin_id"`
	RoleID  uuid.UUID `json:"role_id"`
}

type AuditEvent struct {
	ID           uuid.UUID          `json:"id"`
	ActorType    string             `json:"actor_type"`
	ActorID      *uuid.UUID         `json:"actor_id"`
	Action       string             `json:"action"`
	ResourceType string             `json:"resource_type"`
	ResourceID   *uuid.UUID         `json:"resource_id"`
	BeforeData   []byte             `json:"before_data"`
	AfterData    []byte             `json:"after_data"`
	IpAddress    *netip.Addr        `json:"ip_address"`
	UserAgent    pgtype.Text        `json:"user_agent"`
	RequestID    pgtype.Text        `json:"request_id"`
	TraceID      pgtype.Text        `json:"trace_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Permission struct {
	ID  uuid.UUID `json:"id"`
	Key string    `json:"key"`
}

type Role struct {
	ID        uuid.UUID          `json:"id"`
	Key       string             `json:"key"`
	NameKey   string             `json:"name_key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RolePermission struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

type User struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	PasswordHash    string             `json:"password_hash"`
	Status          string             `json:"status"`
	Locale          string             `json:"locale"`
	Timezone        string             `json:"timezone"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	LastLoginAt     pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
