// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operations.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelOperation = `-- name: CancelOperation :execrows
UPDATE operations
SET status = 'cancelled', finished_at = $2, updated_at = $2
WHERE id = $1 AND status IN ('queued', 'running', 'waiting_provider',
                             'waiting_resource', 'verifying', 'retrying')
`

type CancelOperationParams struct {
	ID         uuid.UUID          `json:"id"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) CancelOperation(ctx context.Context, arg CancelOperationParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelOperation, arg.ID, arg.FinishedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimQueuedOperation = `-- name: ClaimQueuedOperation :one
UPDATE operations
SET status = 'running', started_at = $1, updated_at = $1
WHERE id = (
  SELECT o.id FROM operations o
  WHERE o.status = 'queued'
  ORDER BY o.created_at
  FOR UPDATE SKIP LOCKED
  LIMIT 1
)
RETURNING id, type, resource_type, resource_id, status, phase, progress, message_key, provider_id, provider_operation_id, idempotency_key, retryable, retry_count, max_retries, run_after, error_code, error_message, trace_id, started_at, finished_at, created_at, updated_at
`

// The claim: one worker takes one queued operation. SKIP LOCKED means N workers
// on the same database each take distinct rows and none of them waits.
func (q *Queries) ClaimQueuedOperation(ctx context.Context, startedAt pgtype.Timestamptz) (Operation, error) {
	row := q.db.QueryRow(ctx, claimQueuedOperation, startedAt)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ResourceType,
		&i.ResourceID,
		&i.Status,
		&i.Phase,
		&i.Progress,
		&i.MessageKey,
		&i.ProviderID,
		&i.ProviderOperationID,
		&i.IdempotencyKey,
		&i.Retryable,
		&i.RetryCount,
		&i.MaxRetries,
		&i.RunAfter,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.TraceID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimRetryableOperation = `-- name: ClaimRetryableOperation :one
UPDATE operations
SET status = 'running', started_at = COALESCE(started_at, $1), updated_at = $1,
    -- The new attempt has not failed yet: the previous code cleared here is the
    -- one the row showed while it waited, and the runner records a fresh one if
    -- this attempt fails too.
    error_code = NULL, error_message = NULL
WHERE id = (
  SELECT o.id FROM operations o
  WHERE o.status = 'retrying' AND o.run_after <= $2
  ORDER BY o.updated_at
  FOR UPDATE SKIP LOCKED
  LIMIT 1
)
RETURNING id, type, resource_type, resource_id, status, phase, progress, message_key, provider_id, provider_operation_id, idempotency_key, retryable, retry_count, max_retries, run_after, error_code, error_message, trace_id, started_at, finished_at, created_at, updated_at
`

type ClaimRetryableOperationParams struct {
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	RunAfter  pgtype.Timestamptz `json:"run_after"`
}

// The claim of a retry whose backoff has elapsed: the machine edge
// retrying → running, with the attempt count already on the row.
func (q *Queries) ClaimRetryableOperation(ctx context.Context, arg ClaimRetryableOperationParams) (Operation, error) {
	row := q.db.QueryRow(ctx, claimRetryableOperation, arg.UpdatedAt, arg.RunAfter)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ResourceType,
		&i.ResourceID,
		&i.Status,
		&i.Phase,
		&i.Progress,
		&i.MessageKey,
		&i.ProviderID,
		&i.ProviderOperationID,
		&i.IdempotencyKey,
		&i.Retryable,
		&i.RetryCount,
		&i.MaxRetries,
		&i.RunAfter,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.TraceID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOperation = `-- name: CreateOperation :exec


INSERT INTO operations (
  id, type, resource_type, resource_id, status, idempotency_key,
  max_retries, trace_id, created_at
) VALUES ($1, $2, $3, $4, 'queued', $5, $6, $7, $8)
`

type CreateOperationParams struct {
	ID             uuid.UUID          `json:"id"`
	Type           string             `json:"type"`
	ResourceType   string             `json:"resource_type"`
	ResourceID     uuid.UUID          `json:"resource_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	MaxRetries     int32              `json:"max_retries"`
	TraceID        string             `json:"trace_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

// The operation queries.
//
// The claim is SKIP LOCKED (ADR-008 §1): N workers each take distinct operations
// and none waits, which is what makes the database a queue without a broker.
// ------------------------------------------------------------------ writes --
func (q *Queries) CreateOperation(ctx context.Context, arg CreateOperationParams) error {
	_, err := q.db.Exec(ctx, createOperation,
		arg.ID,
		arg.Type,
		arg.ResourceType,
		arg.ResourceID,
		arg.IdempotencyKey,
		arg.MaxRetries,
		arg.TraceID,
		arg.CreatedAt,
	)
	return err
}

const createOperationStep = `-- name: CreateOperationStep :exec
INSERT INTO operation_steps (
  id, operation_id, step_key, step_order, status, created_at
) VALUES ($1, $2, $3, $4, 'pending', $5)
`

type CreateOperationStepParams struct {
	ID          uuid.UUID          `json:"id"`
	OperationID uuid.UUID          `json:"operation_id"`
	StepKey     string             `json:"step_key"`
	StepOrder   int32              `json:"step_order"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateOperationStep(ctx context.Context, arg CreateOperationStepParams) error {
	_, err := q.db.Exec(ctx, createOperationStep,
		arg.ID,
		arg.OperationID,
		arg.StepKey,
		arg.StepOrder,
		arg.CreatedAt,
	)
	return err
}

const finishOperationStep = `-- name: FinishOperationStep :execrows
UPDATE operation_steps
SET status = $2, error_code = $3, error_message = $4, finished_at = $5, updated_at = $5
WHERE operation_id = $1 AND step_key = $6 AND status = 'running'
`

type FinishOperationStepParams struct {
	OperationID  uuid.UUID          `json:"operation_id"`
	Status       string             `json:"status"`
	ErrorCode    pgtype.Text        `json:"error_code"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	StepKey      string             `json:"step_key"`
}

func (q *Queries) FinishOperationStep(ctx context.Context, arg FinishOperationStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishOperationStep,
		arg.OperationID,
		arg.Status,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.FinishedAt,
		arg.StepKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const moveOperationToRetrying = `-- name: MoveOperationToRetrying :execrows
UPDATE operations
SET status = 'retrying', retry_count = retry_count + 1, run_after = $2, error_code = $3,
    error_message = $4, updated_at = $5
WHERE id = $1 AND status = $6
`

type MoveOperationToRetryingParams struct {
	ID           uuid.UUID          `json:"id"`
	RunAfter     pgtype.Timestamptz `json:"run_after"`
	ErrorCode    pgtype.Text        `json:"error_code"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Status       string             `json:"status"`
}

// A retry: the attempt count advances and the row waits for its backoff.
func (q *Queries) MoveOperationToRetrying(ctx context.Context, arg MoveOperationToRetryingParams) (int64, error) {
	result, err := q.db.Exec(ctx, moveOperationToRetrying,
		arg.ID,
		arg.RunAfter,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.UpdatedAt,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const openOperationByResource = `-- name: OpenOperationByResource :one
SELECT id, type, resource_type, resource_id, status, phase, progress, message_key, provider_id, provider_operation_id, idempotency_key, retryable, retry_count, max_retries, run_after, error_code, error_message, trace_id, started_at, finished_at, created_at, updated_at FROM operations
WHERE resource_type = $1 AND resource_id = $2
  AND status IN ('queued', 'running', 'waiting_provider', 'waiting_resource', 'verifying', 'retrying')
ORDER BY created_at DESC
LIMIT 1
`

type OpenOperationByResourceParams struct {
	ResourceType string    `json:"resource_type"`
	ResourceID   uuid.UUID `json:"resource_id"`
}

// The guard an action path consults: one live workflow per resource at a
// time. A second click is a conflict, not a second machine working.
func (q *Queries) OpenOperationByResource(ctx context.Context, arg OpenOperationByResourceParams) (Operation, error) {
	row := q.db.QueryRow(ctx, openOperationByResource, arg.ResourceType, arg.ResourceID)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ResourceType,
		&i.ResourceID,
		&i.Status,
		&i.Phase,
		&i.Progress,
		&i.MessageKey,
		&i.ProviderID,
		&i.ProviderOperationID,
		&i.IdempotencyKey,
		&i.Retryable,
		&i.RetryCount,
		&i.MaxRetries,
		&i.RunAfter,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.TraceID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const operationByID = `-- name: OperationByID :one

SELECT id, type, resource_type, resource_id, status, phase, progress, message_key, provider_id, provider_operation_id, idempotency_key, retryable, retry_count, max_retries, run_after, error_code, error_message, trace_id, started_at, finished_at, created_at, updated_at
FROM operations
WHERE id = $1
`

// ------------------------------------------------------------------- reads --
func (q *Queries) OperationByID(ctx context.Context, id uuid.UUID) (Operation, error) {
	row := q.db.QueryRow(ctx, operationByID, id)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ResourceType,
		&i.ResourceID,
		&i.Status,
		&i.Phase,
		&i.Progress,
		&i.MessageKey,
		&i.ProviderID,
		&i.ProviderOperationID,
		&i.IdempotencyKey,
		&i.Retryable,
		&i.RetryCount,
		&i.MaxRetries,
		&i.RunAfter,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.TraceID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const operationByIdempotencyKey = `-- name: OperationByIdempotencyKey :one
SELECT id, type, resource_type, resource_id, status, phase, progress, message_key, provider_id, provider_operation_id, idempotency_key, retryable, retry_count, max_retries, run_after, error_code, error_message, trace_id, started_at, finished_at, created_at, updated_at
FROM operations
WHERE idempotency_key = $1
`

func (q *Queries) OperationByIdempotencyKey(ctx context.Context, idempotencyKey string) (Operation, error) {
	row := q.db.QueryRow(ctx, operationByIdempotencyKey, idempotencyKey)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ResourceType,
		&i.ResourceID,
		&i.Status,
		&i.Phase,
		&i.Progress,
		&i.MessageKey,
		&i.ProviderID,
		&i.ProviderOperationID,
		&i.IdempotencyKey,
		&i.Retryable,
		&i.RetryCount,
		&i.MaxRetries,
		&i.RunAfter,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.TraceID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setOperationPhase = `-- name: SetOperationPhase :execrows
UPDATE operations
SET phase = $2, message_key = $3, updated_at = $4
WHERE id = $1
`

type SetOperationPhaseParams struct {
	ID         uuid.UUID          `json:"id"`
	Phase      pgtype.Text        `json:"phase"`
	MessageKey pgtype.Text        `json:"message_key"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

// The phase carries a name and a message, never a number: progress is derived
// from the steps and the only writer of the progress column is
// SyncOperationProgress, so a workflow cannot report itself further along than
// its finished steps say (docs/07: 进度按步骤映射，不按时间伪造).
func (q *Queries) SetOperationPhase(ctx context.Context, arg SetOperationPhaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, setOperationPhase,
		arg.ID,
		arg.Phase,
		arg.MessageKey,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setOperationProvider = `-- name: SetOperationProvider :execrows
UPDATE operations
SET provider_operation_id = $2, updated_at = $3
WHERE id = $1
`

type SetOperationProviderParams struct {
	ID                  uuid.UUID          `json:"id"`
	ProviderOperationID pgtype.Text        `json:"provider_operation_id"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

// The provider's own identifier for this work, recorded the moment the provider
// accepted the request, so a poll later does not need the request at all.
func (q *Queries) SetOperationProvider(ctx context.Context, arg SetOperationProviderParams) (int64, error) {
	result, err := q.db.Exec(ctx, setOperationProvider, arg.ID, arg.ProviderOperationID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const startOperationStep = `-- name: StartOperationStep :execrows

UPDATE operation_steps
SET status = 'running', attempt = attempt + 1, started_at = $2, updated_at = $2
WHERE operation_id = $1 AND step_key = $3 AND status IN ('pending', 'failed')
`

type StartOperationStepParams struct {
	OperationID uuid.UUID          `json:"operation_id"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	StepKey     string             `json:"step_key"`
}

// ------------------------------------------------------------------ steps --
func (q *Queries) StartOperationStep(ctx context.Context, arg StartOperationStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, startOperationStep, arg.OperationID, arg.StartedAt, arg.StepKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const stepsForOperation = `-- name: StepsForOperation :many
SELECT id, operation_id, step_key, step_order, status, progress, attempt,
       error_code, error_message, started_at, finished_at, created_at, updated_at
FROM operation_steps
WHERE operation_id = $1
ORDER BY step_order
`

func (q *Queries) StepsForOperation(ctx context.Context, operationID uuid.UUID) ([]OperationStep, error) {
	rows, err := q.db.Query(ctx, stepsForOperation, operationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OperationStep{}
	for rows.Next() {
		var i OperationStep
		if err := rows.Scan(
			&i.ID,
			&i.OperationID,
			&i.StepKey,
			&i.StepOrder,
			&i.Status,
			&i.Progress,
			&i.Attempt,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncOperationProgress = `-- name: SyncOperationProgress :execrows
UPDATE operations
SET progress = (
  SELECT COALESCE(SUM(CASE WHEN status IN ('succeeded', 'skipped') THEN 100 ELSE progress END)
         / GREATEST(count(*), 1), 0)
  FROM operation_steps WHERE operation_id = $1
), updated_at = $2
WHERE id = $1
`

type SyncOperationProgressParams struct {
	OperationID uuid.UUID          `json:"operation_id"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// The progress is derived from the steps, never accepted from a caller
// (docs/07: 进度按步骤映射，不按时间伪造).
func (q *Queries) SyncOperationProgress(ctx context.Context, arg SyncOperationProgressParams) (int64, error) {
	result, err := q.db.Exec(ctx, syncOperationProgress, arg.OperationID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const transitionOperation = `-- name: TransitionOperation :execrows

UPDATE operations
SET status = $2, phase = $3, message_key = $4, error_code = $5,
    error_message = $6, updated_at = $7,
    finished_at = CASE WHEN $2::varchar IN ('succeeded', 'failed', 'cancelled')
                       THEN $7::timestamptz ELSE finished_at END
WHERE id = $1 AND status = $8
`

type TransitionOperationParams struct {
	ID           uuid.UUID          `json:"id"`
	Status       string             `json:"status"`
	Phase        pgtype.Text        `json:"phase"`
	MessageKey   pgtype.Text        `json:"message_key"`
	ErrorCode    pgtype.Text        `json:"error_code"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Status_2     string             `json:"status_2"`
}

// ---------------------------------------------------------------- machine --
// A generic conditional transition. The target's own rules are the caller's
// (the machine is enforced in the domain); the statement guarantees that the
// row moves only from the state the caller saw.
func (q *Queries) TransitionOperation(ctx context.Context, arg TransitionOperationParams) (int64, error) {
	result, err := q.db.Exec(ctx, transitionOperation,
		arg.ID,
		arg.Status,
		arg.Phase,
		arg.MessageKey,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.UpdatedAt,
		arg.Status_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
