// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runman.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activeRunmanAgentByNode = `-- name: ActiveRunmanAgentByNode :one
SELECT id, node_id, token_hash, status, last_seen_at, created_at, updated_at FROM runman_agents
WHERE node_id = $1 AND status = 'active'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) ActiveRunmanAgentByNode(ctx context.Context, nodeID string) (RunmanAgent, error) {
	row := q.db.QueryRow(ctx, activeRunmanAgentByNode, nodeID)
	var i RunmanAgent
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.TokenHash,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimRunmanCommands = `-- name: ClaimRunmanCommands :many
UPDATE runman_commands c
SET status = 'delivered', delivered_at = $2, updated_at = $2
WHERE c.id IN (
  SELECT k.id FROM runman_commands k
  WHERE k.agent_id = $1 AND k.status = 'queued'
  ORDER BY k.created_at
  LIMIT 10
)
RETURNING c.id, c.agent_id, c.type, c.idempotency_key, c.payload, c.status, c.result, c.error_code, c.created_at, c.delivered_at, c.finished_at, c.updated_at
`

type ClaimRunmanCommandsParams struct {
	AgentID     uuid.UUID          `json:"agent_id"`
	DeliveredAt pgtype.Timestamptz `json:"delivered_at"`
}

// The claim is one conditional UPDATE over the agent's queued rows: the same
// idiom everywhere else in this codebase guards a transition.
func (q *Queries) ClaimRunmanCommands(ctx context.Context, arg ClaimRunmanCommandsParams) ([]RunmanCommand, error) {
	rows, err := q.db.Query(ctx, claimRunmanCommands, arg.AgentID, arg.DeliveredAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunmanCommand{}
	for rows.Next() {
		var i RunmanCommand
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Type,
			&i.IdempotencyKey,
			&i.Payload,
			&i.Status,
			&i.Result,
			&i.ErrorCode,
			&i.CreatedAt,
			&i.DeliveredAt,
			&i.FinishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeRunmanCommand = `-- name: CompleteRunmanCommand :execrows
UPDATE runman_commands
SET status = $2, result = $3, error_code = $4, finished_at = $5, updated_at = $5
WHERE id = $1 AND status = 'delivered'
`

type CompleteRunmanCommandParams struct {
	ID         uuid.UUID          `json:"id"`
	Status     string             `json:"status"`
	Result     []byte             `json:"result"`
	ErrorCode  pgtype.Text        `json:"error_code"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) CompleteRunmanCommand(ctx context.Context, arg CompleteRunmanCommandParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeRunmanCommand,
		arg.ID,
		arg.Status,
		arg.Result,
		arg.ErrorCode,
		arg.FinishedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countPendingRunmanCommands = `-- name: CountPendingRunmanCommands :one
SELECT count(*) FROM runman_commands WHERE agent_id = $1 AND status = 'queued'
`

func (q *Queries) CountPendingRunmanCommands(ctx context.Context, agentID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingRunmanCommands, agentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRunmanAgent = `-- name: CreateRunmanAgent :exec

INSERT INTO runman_agents (id, node_id, token_hash, status)
VALUES ($1, $2, $3, $4)
`

type CreateRunmanAgentParams struct {
	ID        uuid.UUID `json:"id"`
	NodeID    string    `json:"node_id"`
	TokenHash string    `json:"token_hash"`
	Status    string    `json:"status"`
}

// The agent provider's persistence (ADR-013): the credential registry and the
// command queue. All writes are conditional updates; the idempotency key is
// what makes a redelivered command the same command.
func (q *Queries) CreateRunmanAgent(ctx context.Context, arg CreateRunmanAgentParams) error {
	_, err := q.db.Exec(ctx, createRunmanAgent,
		arg.ID,
		arg.NodeID,
		arg.TokenHash,
		arg.Status,
	)
	return err
}

const enqueueRunmanCommand = `-- name: EnqueueRunmanCommand :one
INSERT INTO runman_commands (id, agent_id, type, idempotency_key, payload, status)
VALUES ($1, $2, $3, $4, $5, 'queued')
ON CONFLICT (idempotency_key) DO NOTHING
RETURNING id, agent_id, type, idempotency_key, payload, status, result, error_code, created_at, delivered_at, finished_at, updated_at
`

type EnqueueRunmanCommandParams struct {
	ID             uuid.UUID `json:"id"`
	AgentID        uuid.UUID `json:"agent_id"`
	Type           string    `json:"type"`
	IdempotencyKey string    `json:"idempotency_key"`
	Payload        []byte    `json:"payload"`
}

// The enqueue is the idempotent insert: a second call with the same key reads
// the row the first one wrote.
func (q *Queries) EnqueueRunmanCommand(ctx context.Context, arg EnqueueRunmanCommandParams) (RunmanCommand, error) {
	row := q.db.QueryRow(ctx, enqueueRunmanCommand,
		arg.ID,
		arg.AgentID,
		arg.Type,
		arg.IdempotencyKey,
		arg.Payload,
	)
	var i RunmanCommand
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Type,
		&i.IdempotencyKey,
		&i.Payload,
		&i.Status,
		&i.Result,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.DeliveredAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const runmanAgentByID = `-- name: RunmanAgentByID :one
SELECT id, node_id, token_hash, status, last_seen_at, created_at, updated_at FROM runman_agents WHERE id = $1
`

func (q *Queries) RunmanAgentByID(ctx context.Context, id uuid.UUID) (RunmanAgent, error) {
	row := q.db.QueryRow(ctx, runmanAgentByID, id)
	var i RunmanAgent
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.TokenHash,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const runmanAgentByTokenHash = `-- name: RunmanAgentByTokenHash :one
SELECT id, node_id, token_hash, status, last_seen_at, created_at, updated_at FROM runman_agents WHERE token_hash = $1
`

func (q *Queries) RunmanAgentByTokenHash(ctx context.Context, tokenHash string) (RunmanAgent, error) {
	row := q.db.QueryRow(ctx, runmanAgentByTokenHash, tokenHash)
	var i RunmanAgent
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.TokenHash,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const runmanCommandByID = `-- name: RunmanCommandByID :one
SELECT id, agent_id, type, idempotency_key, payload, status, result, error_code, created_at, delivered_at, finished_at, updated_at FROM runman_commands WHERE id = $1
`

func (q *Queries) RunmanCommandByID(ctx context.Context, id uuid.UUID) (RunmanCommand, error) {
	row := q.db.QueryRow(ctx, runmanCommandByID, id)
	var i RunmanCommand
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Type,
		&i.IdempotencyKey,
		&i.Payload,
		&i.Status,
		&i.Result,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.DeliveredAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const runmanCommandByIdempotencyKey = `-- name: RunmanCommandByIdempotencyKey :one
SELECT id, agent_id, type, idempotency_key, payload, status, result, error_code, created_at, delivered_at, finished_at, updated_at FROM runman_commands WHERE idempotency_key = $1
`

func (q *Queries) RunmanCommandByIdempotencyKey(ctx context.Context, idempotencyKey string) (RunmanCommand, error) {
	row := q.db.QueryRow(ctx, runmanCommandByIdempotencyKey, idempotencyKey)
	var i RunmanCommand
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Type,
		&i.IdempotencyKey,
		&i.Payload,
		&i.Status,
		&i.Result,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.DeliveredAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchRunmanAgent = `-- name: TouchRunmanAgent :execrows
UPDATE runman_agents
SET last_seen_at = $2, updated_at = $2
WHERE id = $1 AND status = 'active'
`

type TouchRunmanAgentParams struct {
	ID         uuid.UUID          `json:"id"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
}

func (q *Queries) TouchRunmanAgent(ctx context.Context, arg TouchRunmanAgentParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchRunmanAgent, arg.ID, arg.LastSeenAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
