// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscription.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscription = `-- name: CreateSubscription :exec

INSERT INTO subscriptions (
  id, user_id, plan_id, status, billing_cycle, price_minor, currency,
  started_at, current_period_start, current_period_end, next_due_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateSubscriptionParams struct {
	ID                 uuid.UUID          `json:"id"`
	UserID             uuid.UUID          `json:"user_id"`
	PlanID             uuid.UUID          `json:"plan_id"`
	Status             string             `json:"status"`
	BillingCycle       string             `json:"billing_cycle"`
	PriceMinor         int64              `json:"price_minor"`
	Currency           string             `json:"currency"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	CurrentPeriodStart pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd   pgtype.Timestamptz `json:"current_period_end"`
	NextDueAt          pgtype.Timestamptz `json:"next_due_at"`
}

// ------------------------------------------------------------------ writes --
func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) error {
	_, err := q.db.Exec(ctx, createSubscription,
		arg.ID,
		arg.UserID,
		arg.PlanID,
		arg.Status,
		arg.BillingCycle,
		arg.PriceMinor,
		arg.Currency,
		arg.StartedAt,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.NextDueAt,
	)
	return err
}

const createSubscriptionInvoice = `-- name: CreateSubscriptionInvoice :exec
INSERT INTO invoices (
  id, invoice_no, user_id, subscription_id, order_id, status, amount_minor, currency, due_at, paid_at
) VALUES ($1, $2, $3, $4, NULL, $5, $6, $7, $8, NULL)
`

type CreateSubscriptionInvoiceParams struct {
	ID             uuid.UUID          `json:"id"`
	InvoiceNo      string             `json:"invoice_no"`
	UserID         uuid.UUID          `json:"user_id"`
	SubscriptionID *uuid.UUID         `json:"subscription_id"`
	Status         string             `json:"status"`
	AmountMinor    int64              `json:"amount_minor"`
	Currency       string             `json:"currency"`
	DueAt          pgtype.Timestamptz `json:"due_at"`
}

// The invoice a renewal is paid against. Born `open`, moved to `paid` by the one
// caller the conditional update below lets through.
func (q *Queries) CreateSubscriptionInvoice(ctx context.Context, arg CreateSubscriptionInvoiceParams) error {
	_, err := q.db.Exec(ctx, createSubscriptionInvoice,
		arg.ID,
		arg.InvoiceNo,
		arg.UserID,
		arg.SubscriptionID,
		arg.Status,
		arg.AmountMinor,
		arg.Currency,
		arg.DueAt,
	)
	return err
}

const createSubscriptionInvoiceItem = `-- name: CreateSubscriptionInvoiceItem :exec
INSERT INTO invoice_items (id, invoice_id, description_i18n, quantity, unit_amount_minor, total_minor)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateSubscriptionInvoiceItemParams struct {
	ID              uuid.UUID `json:"id"`
	InvoiceID       uuid.UUID `json:"invoice_id"`
	DescriptionI18n []byte    `json:"description_i18n"`
	Quantity        int32     `json:"quantity"`
	UnitAmountMinor int64     `json:"unit_amount_minor"`
	TotalMinor      int64     `json:"total_minor"`
}

func (q *Queries) CreateSubscriptionInvoiceItem(ctx context.Context, arg CreateSubscriptionInvoiceItemParams) error {
	_, err := q.db.Exec(ctx, createSubscriptionInvoiceItem,
		arg.ID,
		arg.InvoiceID,
		arg.DescriptionI18n,
		arg.Quantity,
		arg.UnitAmountMinor,
		arg.TotalMinor,
	)
	return err
}

const extendSubscription = `-- name: ExtendSubscription :execrows
UPDATE subscriptions
SET status = 'active', current_period_start = $2, current_period_end = $3,
    next_due_at = $3, grace_until = NULL, version = version + 1, updated_at = $4
WHERE id = $1 AND status IN ('active', 'past_due', 'suspended')
`

type ExtendSubscriptionParams struct {
	ID                 uuid.UUID          `json:"id"`
	CurrentPeriodStart pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd   pgtype.Timestamptz `json:"current_period_end"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

// The renewal: one period of service traded for one payment of money. It runs
// from any of the three live states, because paying during grace (past_due) and
// paying after suspension are both recovery, and docs/07's renew chain ends in
// "extend subscription" for both. `grace_until` is cleared: an active row has
// nothing to resolve.
func (q *Queries) ExtendSubscription(ctx context.Context, arg ExtendSubscriptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, extendSubscription,
		arg.ID,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listSubscriptionsForUser = `-- name: ListSubscriptionsForUser :many
SELECT id, user_id, plan_id, status, billing_cycle, price_minor, currency,
       started_at, current_period_start, current_period_end, next_due_at,
       grace_until, cancel_at_period_end, ended_at, version, created_at, updated_at
FROM subscriptions
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 100
`

func (q *Queries) ListSubscriptionsForUser(ctx context.Context, userID uuid.UUID) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanID,
			&i.Status,
			&i.BillingCycle,
			&i.PriceMinor,
			&i.Currency,
			&i.StartedAt,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.NextDueAt,
			&i.GraceUntil,
			&i.CancelAtPeriodEnd,
			&i.EndedAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWalletForSpend = `-- name: LockWalletForSpend :one
SELECT id, user_id, currency, available_balance_minor
FROM wallets
WHERE user_id = $1 AND currency = $2
FOR UPDATE
`

type LockWalletForSpendParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Currency string    `json:"currency"`
}

type LockWalletForSpendRow struct {
	ID                    uuid.UUID `json:"id"`
	UserID                uuid.UUID `json:"user_id"`
	Currency              string    `json:"currency"`
	AvailableBalanceMinor int64     `json:"available_balance_minor"`
}

// The wallet spend's gate. The row is locked, so two concurrent renewals
// serialize here: the second reads the balance the first left, and a wallet that
// backs one renewal cannot back two. The gate only READS and locks — the
// projection is moved once, by the ledger entries the poster writes in the same
// transaction (ADR-005): gating by decrementing here would move it twice.
func (q *Queries) LockWalletForSpend(ctx context.Context, arg LockWalletForSpendParams) (LockWalletForSpendRow, error) {
	row := q.db.QueryRow(ctx, lockWalletForSpend, arg.UserID, arg.Currency)
	var i LockWalletForSpendRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Currency,
		&i.AvailableBalanceMinor,
	)
	return i, err
}

const markSubscriptionInvoicePaid = `-- name: MarkSubscriptionInvoicePaid :execrows
UPDATE invoices
SET status = 'paid', paid_at = $2, updated_at = $2
WHERE id = $1 AND status = 'open'
`

type MarkSubscriptionInvoicePaidParams struct {
	ID     uuid.UUID          `json:"id"`
	PaidAt pgtype.Timestamptz `json:"paid_at"`
}

// The renewal's settlement is the gate: exactly one caller moves the open invoice
// to `paid`, and that caller — and only that caller — extends the period and
// writes the ledger movement in the same transaction.
func (q *Queries) MarkSubscriptionInvoicePaid(ctx context.Context, arg MarkSubscriptionInvoicePaidParams) (int64, error) {
	result, err := q.db.Exec(ctx, markSubscriptionInvoicePaid, arg.ID, arg.PaidAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const openInvoiceForSubscription = `-- name: OpenInvoiceForSubscription :one
SELECT id, invoice_no, user_id, subscription_id, order_id, status, amount_minor,
       currency, due_at, paid_at, created_at, updated_at
FROM invoices
WHERE subscription_id = $1 AND status = 'open'
`

// Read back the open renewal invoice a lost race left open (ADR-006 §6): both
// sweeps converge on the same bill, so both attempt the same payment.
func (q *Queries) OpenInvoiceForSubscription(ctx context.Context, subscriptionID *uuid.UUID) (Invoice, error) {
	row := q.db.QueryRow(ctx, openInvoiceForSubscription, subscriptionID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNo,
		&i.UserID,
		&i.SubscriptionID,
		&i.OrderID,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.DueAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const orderByIDForSettlement = `-- name: OrderByIDForSettlement :one


SELECT id, order_no, user_id, status, subtotal_minor, discount_minor, total_minor,
       currency, paid_at, created_at, updated_at
FROM orders
WHERE id = $1
`

// The subscription queries.
//
// The machine's writers are conditional updates for the same reason the payment
// settlement is (ADR-005/006): repetition is the normal case for a sweep, and a
// repetition that reads-then-writes is a repetition that doubles.
// ------------------------------------------------------------------- reads --
// The settlement needs the order's lines to know what it activated. Read without
// the user scope: the settlement is the platform acting on its own record, not a
// customer asking for it.
func (q *Queries) OrderByIDForSettlement(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, orderByIDForSettlement, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.UserID,
		&i.Status,
		&i.SubtotalMinor,
		&i.DiscountMinor,
		&i.TotalMinor,
		&i.Currency,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setCancelAtPeriodEnd = `-- name: SetCancelAtPeriodEnd :execrows
UPDATE subscriptions
SET cancel_at_period_end = TRUE, version = version + 1, updated_at = $3
WHERE id = $1 AND user_id = $2 AND status IN ('active', 'past_due')
`

type SetCancelAtPeriodEndParams struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SetCancelAtPeriodEnd(ctx context.Context, arg SetCancelAtPeriodEndParams) (int64, error) {
	result, err := q.db.Exec(ctx, setCancelAtPeriodEnd, arg.ID, arg.UserID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const subscriptionByID = `-- name: SubscriptionByID :one
SELECT id, user_id, plan_id, status, billing_cycle, price_minor, currency,
       started_at, current_period_start, current_period_end, next_due_at,
       grace_until, cancel_at_period_end, ended_at, version, created_at, updated_at
FROM subscriptions
WHERE id = $1
`

func (q *Queries) SubscriptionByID(ctx context.Context, id uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, subscriptionByID, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.BillingCycle,
		&i.PriceMinor,
		&i.Currency,
		&i.StartedAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.NextDueAt,
		&i.GraceUntil,
		&i.CancelAtPeriodEnd,
		&i.EndedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const subscriptionByIDForUser = `-- name: SubscriptionByIDForUser :one
SELECT id, user_id, plan_id, status, billing_cycle, price_minor, currency,
       started_at, current_period_start, current_period_end, next_due_at,
       grace_until, cancel_at_period_end, ended_at, version, created_at, updated_at
FROM subscriptions
WHERE id = $1 AND user_id = $2
`

type SubscriptionByIDForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) SubscriptionByIDForUser(ctx context.Context, arg SubscriptionByIDForUserParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, subscriptionByIDForUser, arg.ID, arg.UserID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.BillingCycle,
		&i.PriceMinor,
		&i.Currency,
		&i.StartedAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.NextDueAt,
		&i.GraceUntil,
		&i.CancelAtPeriodEnd,
		&i.EndedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const subscriptionsPastDeadline = `-- name: SubscriptionsPastDeadline :many
SELECT s.id, s.user_id, s.plan_id, s.status, s.billing_cycle, s.price_minor, s.currency,
       s.started_at, s.current_period_start, s.current_period_end, s.next_due_at,
       s.grace_until, s.cancel_at_period_end, s.ended_at, s.version, s.created_at, s.updated_at,
       p.slug AS plan_slug, p.name_i18n AS plan_name_i18n
FROM subscriptions s
JOIN plans p ON p.id = s.plan_id
WHERE (s.status IN ('active', 'past_due') AND s.current_period_end <= $1)
   OR (s.status = 'suspended' AND s.grace_until <= $1)
`

type SubscriptionsPastDeadlineRow struct {
	ID                 uuid.UUID          `json:"id"`
	UserID             uuid.UUID          `json:"user_id"`
	PlanID             uuid.UUID          `json:"plan_id"`
	Status             string             `json:"status"`
	BillingCycle       string             `json:"billing_cycle"`
	PriceMinor         int64              `json:"price_minor"`
	Currency           string             `json:"currency"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	CurrentPeriodStart pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd   pgtype.Timestamptz `json:"current_period_end"`
	NextDueAt          pgtype.Timestamptz `json:"next_due_at"`
	GraceUntil         pgtype.Timestamptz `json:"grace_until"`
	CancelAtPeriodEnd  bool               `json:"cancel_at_period_end"`
	EndedAt            pgtype.Timestamptz `json:"ended_at"`
	Version            int64              `json:"version"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	PlanSlug           string             `json:"plan_slug"`
	PlanNameI18n       []byte             `json:"plan_name_i18n"`
}

// The sweep's work list: everything alive whose calendar deadline has passed.
// For `active`/`past_due` rows the deadline is the period's end; for `suspended`
// rows `grace_until` carries the state's own deadline — the instant by which the
// current state must be resolved — which is the period's grace while past_due and
// the expiry deadline once suspended. One column, one meaning: the resolution
// deadline of the state the row is in.
// The plan join is for the renewal invoice's line: the bill speaks in the plan's
// own words, as every invoice line does.
func (q *Queries) SubscriptionsPastDeadline(ctx context.Context, currentPeriodEnd pgtype.Timestamptz) ([]SubscriptionsPastDeadlineRow, error) {
	rows, err := q.db.Query(ctx, subscriptionsPastDeadline, currentPeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubscriptionsPastDeadlineRow{}
	for rows.Next() {
		var i SubscriptionsPastDeadlineRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanID,
			&i.Status,
			&i.BillingCycle,
			&i.PriceMinor,
			&i.Currency,
			&i.StartedAt,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.NextDueAt,
			&i.GraceUntil,
			&i.CancelAtPeriodEnd,
			&i.EndedAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PlanSlug,
			&i.PlanNameI18n,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionSubscription = `-- name: TransitionSubscription :execrows
UPDATE subscriptions
SET status = $2, grace_until = $3, ended_at = $4,
    cancel_at_period_end = CASE WHEN $2 = 'cancelled' THEN FALSE
                                ELSE subscriptions.cancel_at_period_end END,
    version = version + 1, updated_at = $5
WHERE id = $1 AND status = $6
  AND ($2 NOT IN ('past_due', 'cancelled') OR current_period_end <= $5)
`

type TransitionSubscriptionParams struct {
	ID         uuid.UUID          `json:"id"`
	Status     string             `json:"status"`
	GraceUntil pgtype.Timestamptz `json:"grace_until"`
	EndedAt    pgtype.Timestamptz `json:"ended_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	Status_2   string             `json:"status_2"`
}

// The conditional transition: the row moves only from the state the caller saw.
// A zero-row result means another writer moved it first, which is the sweep
// racing itself and losing — the answer, not a failure.
// Two of the targets are calendar-bound, and the state alone cannot vouch for
// them: a sweep holding a stale read of an `active` row must not mark it past
// due — or cancel it — if a concurrent renewal has already pushed the period
// into the future. So `past_due` and `cancelled` additionally require the period
// to have actually ended, read from the row as it is now, not as it was read.
// The cancellation flag is part of the state it belongs to: reaching `cancelled`
// is the flag being honoured, so it is cleared with the row; every other target
// leaves the customer's request exactly as they made it.
func (q *Queries) TransitionSubscription(ctx context.Context, arg TransitionSubscriptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, transitionSubscription,
		arg.ID,
		arg.Status,
		arg.GraceUntil,
		arg.EndedAt,
		arg.UpdatedAt,
		arg.Status_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
