// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_surface.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const closeTicket = `-- name: CloseTicket :execrows
UPDATE tickets
SET status = 'closed', closed_at = $3, updated_at = $3
WHERE id = $1 AND user_id = $2 AND status <> 'closed'
`

type CloseTicketParams struct {
	ID       uuid.UUID          `json:"id"`
	UserID   uuid.UUID          `json:"user_id"`
	ClosedAt pgtype.Timestamptz `json:"closed_at"`
}

func (q *Queries) CloseTicket(ctx context.Context, arg CloseTicketParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeTicket, arg.ID, arg.UserID, arg.ClosedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createTicket = `-- name: CreateTicket :exec

INSERT INTO tickets (id, ticket_no, user_id, subject, status, priority)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateTicketParams struct {
	ID       uuid.UUID `json:"id"`
	TicketNo string    `json:"ticket_no"`
	UserID   uuid.UUID `json:"user_id"`
	Subject  string    `json:"subject"`
	Status   string    `json:"status"`
	Priority string    `json:"priority"`
}

// -------------------------------------------------------------------- tickets --
func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) error {
	_, err := q.db.Exec(ctx, createTicket,
		arg.ID,
		arg.TicketNo,
		arg.UserID,
		arg.Subject,
		arg.Status,
		arg.Priority,
	)
	return err
}

const createTicketMessage = `-- name: CreateTicketMessage :exec
INSERT INTO ticket_messages (id, ticket_id, sender_type, sender_id, message)
VALUES ($1, $2, $3, $4, $5)
`

type CreateTicketMessageParams struct {
	ID         uuid.UUID  `json:"id"`
	TicketID   uuid.UUID  `json:"ticket_id"`
	SenderType string     `json:"sender_type"`
	SenderID   *uuid.UUID `json:"sender_id"`
	Message    string     `json:"message"`
}

func (q *Queries) CreateTicketMessage(ctx context.Context, arg CreateTicketMessageParams) error {
	_, err := q.db.Exec(ctx, createTicketMessage,
		arg.ID,
		arg.TicketID,
		arg.SenderType,
		arg.SenderID,
		arg.Message,
	)
	return err
}

const instanceByIDForUser = `-- name: InstanceByIDForUser :one


SELECT i.id, i.subscription_id, i.node_id, i.provider_id, i.provider_instance_id, i.name, i.desired_state, i.observed_state, i.cpu_cores, i.memory_mb, i.disk_gb, i.traffic_limit_gb, i.bandwidth_mbps, i.image_id, i.primary_ipv4, i.primary_ipv6, i.last_synced_at, i.version, i.created_at, i.updated_at, i.deleted_at
FROM instances i
JOIN subscriptions s ON s.id = i.subscription_id
WHERE i.id = $1 AND s.user_id = $2 AND i.deleted_at IS NULL
`

type InstanceByIDForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// The customer's own surface (ADR-011): reads whose ownership is the join
// itself, plus the ticket writes the support page needs. A query that cannot
// name the caller's user id in its WHERE clause does not belong in this file.
// ------------------------------------------------------------------ instances --
// The instance detail: one row, the caller's own, or none at all. The join is
// the authorization; there is no second fetch-and-compare step.
func (q *Queries) InstanceByIDForUser(ctx context.Context, arg InstanceByIDForUserParams) (Instance, error) {
	row := q.db.QueryRow(ctx, instanceByIDForUser, arg.ID, arg.UserID)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.NodeID,
		&i.ProviderID,
		&i.ProviderInstanceID,
		&i.Name,
		&i.DesiredState,
		&i.ObservedState,
		&i.CpuCores,
		&i.MemoryMb,
		&i.DiskGb,
		&i.TrafficLimitGb,
		&i.BandwidthMbps,
		&i.ImageID,
		&i.PrimaryIpv4,
		&i.PrimaryIpv6,
		&i.LastSyncedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const instanceNetworksByInstance = `-- name: InstanceNetworksByInstance :many
SELECT id, instance_id, type, address, gateway, prefix, provider_network_id, created_at FROM instance_networks WHERE instance_id = $1 ORDER BY created_at
`

func (q *Queries) InstanceNetworksByInstance(ctx context.Context, instanceID uuid.UUID) ([]InstanceNetwork, error) {
	rows, err := q.db.Query(ctx, instanceNetworksByInstance, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstanceNetwork{}
	for rows.Next() {
		var i InstanceNetwork
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.Type,
			&i.Address,
			&i.Gateway,
			&i.Prefix,
			&i.ProviderNetworkID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const instanceOwner = `-- name: InstanceOwner :one
SELECT s.user_id AS owner_id
FROM instances i
JOIN subscriptions s ON s.id = i.subscription_id
WHERE i.id = $1 AND i.deleted_at IS NULL
`

// The user id behind an instance, for the operation ownership check.
func (q *Queries) InstanceOwner(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, instanceOwner, id)
	var owner_id uuid.UUID
	err := row.Scan(&owner_id)
	return owner_id, err
}

const invoiceByIDForUser = `-- name: InvoiceByIDForUser :one
SELECT id, invoice_no, user_id, subscription_id, order_id, status, amount_minor, currency, due_at, paid_at, created_at, updated_at FROM invoices WHERE id = $1 AND user_id = $2
`

type InvoiceByIDForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) InvoiceByIDForUser(ctx context.Context, arg InvoiceByIDForUserParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, invoiceByIDForUser, arg.ID, arg.UserID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNo,
		&i.UserID,
		&i.SubscriptionID,
		&i.OrderID,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.DueAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const invoiceItemsByInvoice = `-- name: InvoiceItemsByInvoice :many
SELECT id, invoice_id, description_i18n, quantity, unit_amount_minor, total_minor, created_at FROM invoice_items WHERE invoice_id = $1 ORDER BY created_at
`

func (q *Queries) InvoiceItemsByInvoice(ctx context.Context, invoiceID uuid.UUID) ([]InvoiceItem, error) {
	rows, err := q.db.Query(ctx, invoiceItemsByInvoice, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvoiceItem{}
	for rows.Next() {
		var i InvoiceItem
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.DescriptionI18n,
			&i.Quantity,
			&i.UnitAmountMinor,
			&i.TotalMinor,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const invoicesForUser = `-- name: InvoicesForUser :many

SELECT id, invoice_no, user_id, subscription_id, order_id, status, amount_minor, currency, due_at, paid_at, created_at, updated_at FROM invoices WHERE user_id = $1 ORDER BY created_at DESC LIMIT 100
`

// ------------------------------------------------------------------- invoices --
func (q *Queries) InvoicesForUser(ctx context.Context, userID uuid.UUID) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, invoicesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceNo,
			&i.UserID,
			&i.SubscriptionID,
			&i.OrderID,
			&i.Status,
			&i.AmountMinor,
			&i.Currency,
			&i.DueAt,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationRead = `-- name: MarkNotificationRead :execrows
UPDATE notifications SET read_at = $2 WHERE id = $1 AND user_id = $3 AND read_at IS NULL
`

type MarkNotificationReadParams struct {
	ID     uuid.UUID          `json:"id"`
	ReadAt pgtype.Timestamptz `json:"read_at"`
	UserID *uuid.UUID         `json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.ReadAt, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const notificationsForUser = `-- name: NotificationsForUser :many

SELECT id, user_id, admin_id, type, title_key, message_key, parameters, severity, read_at, created_at FROM notifications WHERE user_id = $1 ORDER BY created_at DESC LIMIT 50
`

// -------------------------------------------------------------- notifications --
func (q *Queries) NotificationsForUser(ctx context.Context, userID *uuid.UUID) ([]Notification, error) {
	rows, err := q.db.Query(ctx, notificationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AdminID,
			&i.Type,
			&i.TitleKey,
			&i.MessageKey,
			&i.Parameters,
			&i.Severity,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const portForwardsByInstance = `-- name: PortForwardsByInstance :many
SELECT id, instance_id, protocol, public_ip, public_port, guest_port, description, status, provider_mapping_id, created_at, updated_at FROM port_forwards WHERE instance_id = $1 ORDER BY created_at
`

func (q *Queries) PortForwardsByInstance(ctx context.Context, instanceID uuid.UUID) ([]PortForward, error) {
	rows, err := q.db.Query(ctx, portForwardsByInstance, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PortForward{}
	for rows.Next() {
		var i PortForward
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.Protocol,
			&i.PublicIp,
			&i.PublicPort,
			&i.GuestPort,
			&i.Description,
			&i.Status,
			&i.ProviderMappingID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setInstanceDesiredState = `-- name: SetInstanceDesiredState :execrows
UPDATE instances
SET desired_state = $2, version = version + 1, updated_at = $3
WHERE id = $1 AND desired_state <> $2 AND deleted_at IS NULL
`

type SetInstanceDesiredStateParams struct {
	ID           uuid.UUID          `json:"id"`
	DesiredState string             `json:"desired_state"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// The state an action asks for. The conditional UPDATE is the same idiom the
// commerce transitions use: the WHERE names the state the row must be in.
func (q *Queries) SetInstanceDesiredState(ctx context.Context, arg SetInstanceDesiredStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, setInstanceDesiredState, arg.ID, arg.DesiredState, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setInstanceImage = `-- name: SetInstanceImage :execrows
UPDATE instances
SET image_id = $2, version = version + 1, updated_at = $3
WHERE id = $1 AND deleted_at IS NULL
`

type SetInstanceImageParams struct {
	ID        uuid.UUID          `json:"id"`
	ImageID   pgtype.Text        `json:"image_id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SetInstanceImage(ctx context.Context, arg SetInstanceImageParams) (int64, error) {
	result, err := q.db.Exec(ctx, setInstanceImage, arg.ID, arg.ImageID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const subscriptionOwner = `-- name: SubscriptionOwner :one

SELECT user_id AS owner_id FROM subscriptions WHERE id = $1
`

// ------------------------------------------------- operation ownership joins --
// The user id behind a subscription-typed operation.
func (q *Queries) SubscriptionOwner(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, subscriptionOwner, id)
	var owner_id uuid.UUID
	err := row.Scan(&owner_id)
	return owner_id, err
}

const ticketByIDForUser = `-- name: TicketByIDForUser :one
SELECT id, ticket_no, user_id, subject, status, priority, created_at, updated_at, closed_at FROM tickets WHERE id = $1 AND user_id = $2
`

type TicketByIDForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// The join is the authorization, as everywhere in this file.
func (q *Queries) TicketByIDForUser(ctx context.Context, arg TicketByIDForUserParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, ticketByIDForUser, arg.ID, arg.UserID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.TicketNo,
		&i.UserID,
		&i.Subject,
		&i.Status,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const ticketMessagesByTicket = `-- name: TicketMessagesByTicket :many
SELECT id, ticket_id, sender_type, sender_id, message, created_at FROM ticket_messages WHERE ticket_id = $1 ORDER BY created_at
`

func (q *Queries) TicketMessagesByTicket(ctx context.Context, ticketID uuid.UUID) ([]TicketMessage, error) {
	rows, err := q.db.Query(ctx, ticketMessagesByTicket, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketMessage{}
	for rows.Next() {
		var i TicketMessage
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.SenderType,
			&i.SenderID,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ticketsForUser = `-- name: TicketsForUser :many
SELECT id, ticket_no, user_id, subject, status, priority, created_at, updated_at, closed_at FROM tickets WHERE user_id = $1 ORDER BY created_at DESC LIMIT 100
`

func (q *Queries) TicketsForUser(ctx context.Context, userID uuid.UUID) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, ticketsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.TicketNo,
			&i.UserID,
			&i.Subject,
			&i.Status,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchTicketOnMessage = `-- name: TouchTicketOnMessage :execrows
UPDATE tickets
SET status = CASE WHEN $2 = 'user' AND status = 'answered' THEN 'open' ELSE status END,
    updated_at = $3
WHERE id = $1 AND status <> 'closed'
`

type TouchTicketOnMessageParams struct {
	ID        uuid.UUID          `json:"id"`
	Column2   interface{}        `json:"column_2"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// A reply marks the conversation alive again; the owner's reply moves it out
// of answered, because answered means "waiting for the customer".
func (q *Queries) TouchTicketOnMessage(ctx context.Context, arg TouchTicketOnMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchTicketOnMessage, arg.ID, arg.Column2, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const trafficByInstance = `-- name: TrafficByInstance :many
SELECT id, instance_id, period_start, period_end, rx_bytes, tx_bytes, source, created_at FROM traffic_usage WHERE instance_id = $1 ORDER BY period_start DESC LIMIT 12
`

func (q *Queries) TrafficByInstance(ctx context.Context, instanceID uuid.UUID) ([]TrafficUsage, error) {
	rows, err := q.db.Query(ctx, trafficByInstance, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrafficUsage{}
	for rows.Next() {
		var i TrafficUsage
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.RxBytes,
			&i.TxBytes,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unreadNotificationCountForUser = `-- name: UnreadNotificationCountForUser :one
SELECT count(*) FROM notifications WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) UnreadNotificationCountForUser(ctx context.Context, userID *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, unreadNotificationCountForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const walletLedgerForUser = `-- name: WalletLedgerForUser :many
SELECT lt.type AS transaction_type, lt.reference_type, lt.reference_id,
       lt.description, le.direction, le.amount_minor, le.currency, le.created_at
FROM ledger_entries le
JOIN wallets w ON w.id = le.account_id
JOIN ledger_transactions lt ON lt.id = le.transaction_id
WHERE w.user_id = $1
ORDER BY le.created_at DESC
LIMIT 50
`

type WalletLedgerForUserRow struct {
	TransactionType string             `json:"transaction_type"`
	ReferenceType   pgtype.Text        `json:"reference_type"`
	ReferenceID     *uuid.UUID         `json:"reference_id"`
	Description     pgtype.Text        `json:"description"`
	Direction       string             `json:"direction"`
	AmountMinor     int64              `json:"amount_minor"`
	Currency        string             `json:"currency"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

// The truth behind the projection: the caller's wallet accounts' entries,
// joined to their transactions for the description. Append-only, so newest
// first is all the ordering a page needs.
func (q *Queries) WalletLedgerForUser(ctx context.Context, userID uuid.UUID) ([]WalletLedgerForUserRow, error) {
	rows, err := q.db.Query(ctx, walletLedgerForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WalletLedgerForUserRow{}
	for rows.Next() {
		var i WalletLedgerForUserRow
		if err := rows.Scan(
			&i.TransactionType,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.Description,
			&i.Direction,
			&i.AmountMinor,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const walletsForUser = `-- name: WalletsForUser :many

SELECT id, user_id, currency, available_balance_minor, created_at, updated_at FROM wallets WHERE user_id = $1 ORDER BY currency
`

// --------------------------------------------------------------------- wallet --
// The projection: what the customer can spend, per currency.
func (q *Queries) WalletsForUser(ctx context.Context, userID uuid.UUID) ([]Wallet, error) {
	rows, err := q.db.Query(ctx, walletsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Wallet{}
	for rows.Next() {
		var i Wallet
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Currency,
			&i.AvailableBalanceMinor,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
